### ISSUE TITLE
setup-java support for jre 1.6

### ISSUE THREAD

**Issue by Bharani-Schawk** [actions/setup-java#103]
Hello Team,

Im trying to setup a workflow with java 1.6 and maven 3.2.5 (stCarolas/setup-maven@v3). Im getting **"Exception in thread "main" java.lang.UnsupportedClassVersionError: org/codehaus/plexus/classworlds/launcher/Launcher : Unsupported major.minor version 51.0"** error in Ubuntu-latest runner.

I see your readme file says it has support for version 6. Let me know any workaround here.

Thanks,
Bharani.

**Comment by AustinShalit** [comment]
It looks like the Action worked correctly. `Unsupported major.minor version 51.0` means that you are trying to run Java byte code compiled for JDK 1.7 on an older version of Java. The root of this is the version of Maven you are using. Maven 3.1+ requires Java 1.7 or later.

**Comment by AustinShalit** [comment]
If I had to guess what is happening is that the setup-maven action you are using is not setting up maven version 3.2.5 (which was the last version to support Java 6.

**Comment by Bharani-Schawk** [comment]
Hi @AustinShalit 
thanks for the feedback. let me check on this and come back.

**Comment by Bharani-Schawk** [comment]
Hi,
im downloading the jre 1.6 and setting it up.
thanks.
