### ISSUE TITLE
README outdated WRT java 14 and 15

### ISSUE THREAD

**Issue by galderz** [actions/setup-java#107]
Both Java 14 and 15 are already released, they are not ea any more.

**Comment by giltene** [comment]
While we can and probably should update the README regularly to include the latest available versions (e.g. add 14 and 15 to the list of non-EA versions in the examples, and 16-ea to the EA versions), the language for the README should aim to remain correct even if we don't update it every 6 months. The version numbers in the README are examples of how to use the version specification syntax and not necessarily an exhaustive list of what is available at a given point in time.

We don't need to necessarily remove all older EA version specification examples each time when the non-EA version comes out (this will happen every 6 months). The EA version specifications for 14 and 15 still work, as stated, and will continue to work. It's just that there are also non-EA versions of the same.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released `setup-java@v2` and updated documentation according to it. You can see supported versions for each distribution through their official sites.
