### ISSUE TITLE
Action's execution says "no such file or directory, stat" but the file is present

### ISSUE THREAD

**Issue by eddumelendez** [actions/setup-java#110]
Currently, using github actions I am downloading jdk using sdkman api and once downloaded a output is set which is sent to the next action, in this case is `setup-java` but I am getting `no such file or directory, stat` when the file is indeed present.  You can find a build example [here](https://github.com/sdkman/sdkman-action/runs/1253583963?check_suite_focus=true)

Currently the filename is `amazon-corretto-11.0.8.10.1-macosx-x64.tar.gz` but if it is renamed to `java-corretto.tar.gz` then `setup-java` can find it.

**Comment by dmitry-shibanov** [comment]
Hello, @eddumelendez . Is it still an issue for you ?

**Comment by dmitry-shibanov** [comment]
Hello @eddumelendez . Just a gentle ping.

**Comment by dmitry-shibanov** [comment]
Hello @eddumelendez, I'm closing this issue since because as I checked your repository, the issue was fixed from your side. If you have any concerns feel free to reopen the issue.
