### ISSUE TITLE
set-env is deprecated

### ISSUE THREAD

**Issue by ifero** [actions/setup-java#114]
As mentioned [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) and [here](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/)
set-env has been deprecated.

![image](https://user-images.githubusercontent.com/1201561/99783889-52e85000-2b1b-11eb-84f3-3695ef748137.png)

do you have an ETA for a fix?

**Comment by Boris-de** [comment]
Are you using an old version of setup-java? I had the same issue when using a 1.3 version, but it worked when updating to the latest version.

**Comment by ifero** [comment]
my bad, thanks @Boris-de
