### ISSUE TITLE
GPG fails to sign because settings.xml isn't written

### ISSUE THREAD

**Issue by tcurdt** [actions/setup-java#120]
**Description:**

I am trying push a release to Maven Central but I am getting

```
gpg: signing failed: Bad passphrase
```

Looking at the file system it seems like the `settings.xml` is not getting written.

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

https://github.com/tcurdt/jdependency/blob/master/.github/workflows/release-ossrh.yml

**Expected behavior:**

It would be nice to have some log output that the `settings.xml` gets written - and where it actually gets written to.
That would also confirm it actually gets written.

**Actual behavior:**

It looks like the `settings.xml` is missing - which is why the signing fails.

**Comment by dmitry-shibanov** [comment]
Hello @tcurdt. The default path for `settings.xml` is [~/.m2](https://github.com/actions/setup-java/blob/089d28c90b722d60475fdf3bf4585acd9bed4ee5/action.yml#L39-L41). If I understood well, you want to add `settings.xml` in the root of your project. Could you please try to specify path with `settings-path: ${{ github.workspace }}` ?
As I saw in the logs task writes location of settings.xml: `overwriting existing file /home/runner/.m2/settings.xml`

**Comment by tcurdt** [comment]
I totally missed the `overwriting existing file /home/runner/.m2/settings.xml`. Thanks for the pointer.

[The docs say](https://github.com/actions/setup-java) it is getting created in `$HOME`. I guess that should be `$HOME/.m2` and tripped me up. But given that it then *is* the correct location it might not be the reason that it is failing.

I assume `importing private key` just means the key got written into the settings file? No indication if the passphrase is correct or not?

**Comment by tcurdt** [comment]
I managed to get it working in the end. Would be nice to have some better logging.
