### ISSUE TITLE
Post job phase fails to remove private key

### ISSUE THREAD

**Issue by tbossi** [actions/setup-java#128]
**Description:**
If you have multiple setup steps with different settings but same `gpg-private-key` every time, then post job phase fails with the following message:
```
Post job cleanup.
removing private key from keychain
Error: failed to remove private key
```

**Task version:**
actions/setup-java@v1

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

1. Create a workflow with two (or more) setup-java steps, with different settings but same `gpg-private-key` each time.
2. Run the workflow.
3. The first post job phase completes successfully.
4. All the other post job phases fail with the error "failed to remove private key".

**Expected behavior:**
Post job phase should try to remove the private key if still present, but not fail if a previous step have already removed it.

**Actual behavior:**
Post job phase fails trying to remove a private key already removed.

**Comment by dmitry-shibanov** [comment]
Hello @tbossi. Could you please define the `gpg-private-key` only for the first call of `setup-java`.

**Comment by tbossi** [comment]
Oh, I hadn't thought of that...
That way it works, thanks!

**Comment by dmitry-shibanov** [comment]
Hello @tbossi. Thank you for your response. I'm closing the issue because proposed solution has helped.

**Comment by eriksw** [comment]
@dmitry-shibanov This is a recurring papercut. Is there any way setup-java could be fixed to not require the workaround?
