### ISSUE TITLE
Does not seem to work with java-version 17

### ISSUE THREAD

**Issue by ilgrosso** [actions/setup-java#149]
With java-version: "17":

```
Run actions/setup-java@v1.4.3
  with:
    java-version: 17
    java-package: jdk
    architecture: x64
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
Error: No valid download found for version 17.x and package jdk. Check https://static.azul.com/zulu/bin/ for a list of valid versions or download your own jdk file and add the jdkFile argument
```

For example, https://static.azul.com/zulu/bin/ is listing `zulu17.0.33-ea-jdk17.0.0-ea.12-linux_x64.tar.gz ` which seems to match the pattern as for JDK 16:  `zulu16.28.11-ca-jdk16.0.0-linux_x64.tar.gz  `

**Comment by maxim-lobanov** [comment]
Hello @ilgrosso , since 17.x is not GA yet - `java-version` should be specified as `17-ea`

**Comment by ilgrosso** [comment]
Ouch @maxim-lobanov I should have put some more attention, as it seems... thank you!
