### ISSUE TITLE
Make the distribution input field optional

### ISSUE THREAD

**Issue by hantsy** [actions/setup-java#154]
**Description:**

V2 requires a `distribution` input field which brought breaking changes to v1. Make it optional, set default to `zulu`, thus for most cases, I do not need to change my Github Actions workflow config.

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

After upgrading to v2 in [this pr](https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/110), specify the distribution to `adopt`,  the cacerts import behavior failed in Github actions.
See the log:

https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/110/checks?check_run_id=2270373502

You can review the current version(v1) used in the master branch, it works well.

https://github.com/hantsy/jakartaee9-starter-boilerplate/blob/master/.github/workflows/it-with-arq-liberty-remote.yml

**Comment by dmitry-shibanov** [comment]
Hello @hantsy. It looks like the issue comes from precached java version not from the task itself. As a solution you can run `keytool` with sudo or switch distribution to `zulu`.

**Comment by hantsy** [comment]
What is the default distribution in v1? @dmitry-shibanov

**Comment by konradpabjan** [comment]
Here is a migration guide for `v1` to `v2`. If you want to maintain the same behavior as `v1` you need to specify `zulu`. See: https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md

**Comment by hantsy** [comment]
Changed to `zulu` it works again.

**Comment by dmitry-shibanov** [comment]
Based on [ADR](https://github.com/actions/setup-java/blob/main/docs/adrs/0000-v2-setup-java.md#new-input) we're not planing to make distribution's field optional. If you want to stay with zulu distribution you can see migration guide for `v1` to `v2` [here](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md). We're going to track the initial problem in our repository: https://github.com/actions/virtual-environments/issues/3117
