### ISSUE TITLE
error: No supported distribution was found for input jdkFile

### ISSUE THREAD

**Issue by hantsy** [actions/setup-java#166]
**Description:**
Follow the guide to install custom JDK dist.

https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Installing-custom-Java-package-type

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

Check my workflow file: https://github.com/hantsy/cargotracker/blob/master/.github/workflows/it-with-arq-wildfly-managed.yml#L21

Check the run result: https://github.com/hantsy/cargotracker/runs/2339867024#step:4:2

**Comment by dmitry-shibanov** [comment]
Hello @hantsy. Thank you for report. We had the typo in our documentation, it was fixed in scope of this pull requests:
- https://github.com/actions/setup-java/pull/163
- https://github.com/actions/setup-java/pull/167

You should change `distribution: 'jdkFile'` to `distribution: 'jdkfile'`.
