### ISSUE TITLE
JDK 16 support

### ISSUE THREAD

**Issue by fragaLY** [actions/setup-java#168]
**Description:**
The JDK 16 had been release. Could you please update the versions of supported JDK releases?

2 actionable tasks: 2 executed
Execution failed for task ':compileJava'.
> error: invalid source release: 16

**Comment by dmitry-shibanov** [comment]
Hello @fragaLY. We ran the [task](https://github.com/dmitry-shibanov/testActionTasks/actions/runs/771075303) with 16th version of java for both distributions and it worked as expected. Could you please provide some more information about the issue ?

**Comment by fragaLY** [comment]
My fault, I use deprecated versions of java-setup.

**Comment by dmitry-shibanov** [comment]
No worries, everything is alright. I'm closing the issue but if you face up with other issues feel free to open the new one.

**Comment by iemejia** [comment]
It seems however that the [README](https://github.com/actions/setup-java/blob/main/README.md) is not updated to mention the Java 16 support

**Comment by maxim-lobanov** [comment]
@iemejia , We wouldn't like to maintain the action readme every time when new version is released.
The action allows to download and install any version provided by Zulu and Adopt. If version is available on official site, it will be available in action automatically.

See readme note:
> NOTE: The different distributors can provide discrepant list of available versions / supported configurations. Please refer to the official documentation to see the list of supported versions.

**Comment by iemejia** [comment]
Oh i see thanks for the info :+1:
