### ISSUE TITLE
##[error]tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by jensbaitingerbosch** [actions/setup-java#169]
**Description:**
Were trying to set up a pipeline on a runner behind a corporate proxy. Github Enterprise is running  in the cloud. The Runner has a proxy configured and other actions are running (e.g. actions/checkout) fine. When we try to use the this action, we get the following output:
```
 Set up job
3s
Download action repository 'actions/setup-java@v2'
Current runner version: '2.272.0'
Runner name: 'si0vmc1985'
Machine name: 'si0vmc1985'
Runner is running behind proxy server 'http://172.17.0.1:3128/' for all HTTP requests.
Runner is running behind proxy server 'http://172.17.0.1:3128/' for all HTTPS requests.
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-java@v2'
Run actions/checkout@v2
1s
Resolved version xxxxxxxxxxxxxxxxxxxxxxxxx
Run actions/checkout@v2
Syncing repository: xxxxxxxxxxxxxxxxxxx
Getting Git version info
Deleting the contents of '/local/home/github-runner/_work/xxxxxxxxxxxxxxxxxxxxxxxxx'
The repository will be downloaded using the GitHub REST API
To create a local Git repository instead, add Git 2.18 or higher to the PATH
Downloading the archive
Writing archive to disk
Extracting the archive
/bin/tar xz -C /local/home/github-runner/_work/xxxxxxxxxxxxxxxxx/62f9ecc6-ab19-4f24-934d-821f9d499392 -f /local/home/github-runner/_work/xxxxxxxxxxxxxxxxxxxx/62f9ecc6-ab19-4f24-934d-821f9d499392.tar.gz
Resolved version xxxxxxxxxxxxxxxxxxxxxxxx
Set up JDK 11
1s
    overwrite-settings: true
Run actions/setup-java@v2
  with:
    java-version: 11
    distribution: adopt
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
Trying to resolve the latest version from remote
(node:30582) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
##[error]tunneling socket could not be established, statusCode=407
```

The strange thing is, that the configured proxy on that VM is a cntlm that handles the proxy authentication against the corporate proxy and provides a proxy interface  for all apps on the same host without proxy authentication required. 

My gutfeeling is that the corporate proxy might block something (the error message tells something like a tunneling, which is something our proxy might block. 

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Comment by dmitry-shibanov** [comment]
Hello @jensbaitingerbosch. Thank you for your report. Sorry for the long time response. It looks like setup-java can't be used with proxy because of the [http-client](https://github.com/actions/http-client). Checkout step passes because it does not use http-client. As I know http-client has extra configuration to pass proxy that is why we can track your issue as feature request to add logic for the action to pass proxy.

**Comment by dmitry-shibanov** [comment]
Hello @jensbaitingerbosch. I'm closing the issue with the description above. Feel free to create new issue as a feature request.
