### ISSUE TITLE
Offer Amazon Coretto in addition to others JDKs

### ISSUE THREAD

**Issue by felipebonezi** [actions/setup-java#176]
**Description:**
Should be downloadable e.g. from https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

**Justification:**
Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the Open Java Development Kit (OpenJDK). Corretto comes with long-term support that includes performance enhancements and security fixes. Corretto is certified as compatible with the Java SE standard and is used internally at Amazon for many production services. With Corretto, you can develop and run Java applications on operating systems such as Amazon Linux 2, Windows, and macOS.

**Are you willing to submit a PR?**

Maybe, I'll check how to contribute.

**Comment by giltene** [comment]
This is a dup of https://github.com/actions/setup-java/issues/68 I think.

**Comment by dmitry-shibanov** [comment]
Hello @felipebonezi. We have the similar issue about [adding support for Amazon Coretto binaries](https://github.com/actions/setup-java/issues/68#issuecomment-832200670). I'm closing the issue as duplicate but feel free to submit a pull request.
Thank you for note @giltene
