### ISSUE TITLE
GPG Secret key is not detected during mvn deploy

### ISSUE THREAD

**Issue by byronlin13** [actions/setup-java#177]
**Description:**
I followed the `Publishing using Apache Maven` example in the [advanced-usage.md
](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven) to specify my gpg private key in my [workflow](https://github.com/byronlin13/test-release-automation-java/blob/main/.github/workflows/publish_to_maven_staging.yml).

However when it executes `mvn deploy -P release`, it [fails](https://github.com/byronlin13/test-release-automation-java/runs/2507283282?check_suite_focus=true#step:4:8207) and returns the following error:
```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
* My [simple java repo](https://github.com/byronlin13/test-release-automation-java) which attempts to release to maven staging via GitHub actions
* [Github actions file](https://github.com/byronlin13/test-release-automation-java/blob/main/.github/workflows/publish_to_maven_staging.yml)
* [POM.xml](https://github.com/byronlin13/test-release-automation-java/blob/main/pom.xml)
* I have set the secret values in my repo: 
<img width="953" alt="Screen Shot 2021-05-05 at 1 12 15 AM" src="https://user-images.githubusercontent.com/57543366/117113242-0e561700-ad3f-11eb-826d-51a89a16c397.png">

**Expected behavior:**
* The deployment to Maven staging should be successful. I manually executed the steps successfully.

**Actual behavior:**
* Fails during `mvn deploy -P release` with the following error:
```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Comment by dmitry-shibanov** [comment]
Hello @byronlin13. Thank you for your report. Could you please try to add [Extra setup for pom.xml](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#extra-setup-for-pomxml). Also could you please check notes about settings.xml in section about generation in [Publishing using Apache Maven](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven). As I can see you have your own settings.xml file, where you setup `<passphrase>${env.GPG_PASSPHRASE}</passphrase>`, but you don't have GPG_PASSPHRASE environment variable. You declare `MAVEN_GPG_PASSPHRASE`  on `Publish to Apache Maven Central`.

**Comment by byronlin13** [comment]
@dmitry-shibanov thank you for your prompt response.

I've done the following:
* I removed my settings.xml file in my [repo](https://github.com/byronlin13/test-release-automation-java)
* I've added the extra setup in my [pom file](https://github.com/byronlin13/test-release-automation-java/blob/main/pom.xml#L84-L90)

But the GitHub actions still [fail](https://github.com/byronlin13/test-release-automation-java/actions/runs/814204033) with the same error

**Comment by byronlin13** [comment]
I found out the issue, when I was exporting the GPG secret key, I was following this [GitHub documentation](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-gpg-key#generating-a-gpg-key) which says to execute: `gpg --armor --export 3AA5C34371567BD2`

I saw that in the [advanced-usage.md](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#gpg), it says to execute `gpg --armor --export-secret-keys YOUR_ID`

I ran this and it worked. Sorry about the churn.
