### ISSUE TITLE
Some JVMs are broken, missing files or API access

### ISSUE THREAD

**Issue by bmarwell** [actions/setup-java#183]
**Description:**

Some JVMs, only on ubuntu, can fail with this error:

`IOException: /opt/hostedtoolcache/java_adopt-openj9_jdk/11.0.11-9/x64/lib/jrt-fs.jar not exist`

**Task version:**

2.1.0

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

* https://github.com/apache/shiro/pull/301/checks?check_run_id=2685704321
* os: ubuntu, dist: openj9 (always), adopt-hotspot (16 only), zulu (11 + 16)
* running the aspectj-maven-plugin from https://github.com/dev-aspectj/aspectj-maven-plugin

**Expected behavior:**

Runs fine without error

**Actual behavior:**

`IOException: /opt/hostedtoolcache/java_adopt-openj9_jdk/11.0.11-9/x64/lib/jrt-fs.jar not exist`

Additional info:
ASF CI (Jenkins) will run just fine with the same JVMs. Therefore this is most probably a github problem.

**Comment by dmitry-shibanov** [comment]
Hello, @bmarwell. Thank you for your report. I can't explain it exactly, but it looks like that during `mvn build`, it tries to find `jrt-fs.jar` in lower case path, that is why it can't find `jrt-fs.jar`. The real path is `/opt/hostedtoolcache/Java_Adopt-OpenJ9_jdk//11.0.11-9/x64/lib/jrt-fs.jar`. I run action with lower case directory and it [passed](https://github.com/testacc-art/shiro/actions/runs/885228283). Could it be the issue with package or maven ?
We're still continuing investigation.

**Comment by bmarwell** [comment]
Hi, yes it could be an issue with aspectj. I will try to update it. Thanks for the information!

**Comment by bmarwell** [comment]
Fixed with an update of `aspectj`.
