### ISSUE TITLE
Update.md

### ISSUE THREAD

**Issue by katelynnashley95icloudcom** [actions/setup-java#189]
**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by katelynnashley95icloudcom** [comment]
> **Description:**
> Describe your proposal.
> **Updating** **All**
> **Justification:**
> Justification or a use case for your proposal.
> @katelynnashley95icloudcom @clarkbw @bryanmacfarlane @chrispat @katelynnashley95icloudcom @
> **Are you willing to submit a PR?**
>

**Comment by dmitry-shibanov** [comment]
Close as spam.
