### ISSUE TITLE
Add support for Eclipse Temurin

### ISSUE THREAD

**Issue by giltene** [actions/setup-java#191]
With Eclipse Temurin expected to come out with a July update release for various OpenJDK versions, it would be good to add Temurin as a distribution option in action/setup-java ASAP. The obvious spelling would probably be "temurin", alongside the existing distribution options of "adopt" and "zulu".

**Comment by josephjthomas** [comment]
+1 for OP. Since July, all releases are deployed to Adoptium instead of AdoptOpenJDK. That means, if you specify adopt and version 16 in your workflow, you get 16.0.1+9, but 16.0.2+7 is the newest version. The workflow actively provides outdated Java versions.

**Comment by maxim-lobanov** [comment]
PR with changes has been merged (thank you @joschi for great contribution).
We will release new task version on Monday because we are trying to avoid Friday releases.

**Comment by msgilligan** [comment]
`setup-java@main` with `distribution: 'temurin'` is working for me -- thanks!

**Comment by MaksimZhukov** [comment]
Hello everyone!
We've released a new version (v2.2.0) of setup-java action and updated the major tag accordingly. 
Link to the release: https://github.com/actions/setup-java/releases/tag/v2.2.0
Thanks!

**Comment by MaksimZhukov** [comment]
I'm closing the issue. Feel free to contact us if you have any questions.
