### ISSUE TITLE
Problem matcher for Checkstyle (and possibly others)

### ISSUE THREAD

**Issue by kiancross** [actions/setup-java#197]
**Description:**
Problem matchers for tools such as [Checkstyle](https://checkstyle.sourceforge.io/) (and possibly others).

**Justification:**
Allows annotations on the GitHub interface. It is nicer if these are included in the `setup-java` repo rather than another action. This is available for some actions, such as [`setup-node`](https://github.com/actions/setup-node/blob/main/.github/eslint-stylish.json).

**Are you willing to submit a PR?**
Yes, if you would accept one.

**Comment by dmitry-shibanov** [comment]
Hello @kiancross. Thank you for your report. Could you please describe it a bit more? As I know we have the similar [matcher](https://github.com/actions/setup-java/blob/main/.github/java.json).

**Comment by kiancross** [comment]
Hi @dmitry-shibanov. I have submitted a PR here: https://github.com/actions/setup-java/pull/198.

Checkstyle is a plugin often in Java projects. It would be useful if its output was automatically added to GitHub annotations. This is already done for some actions, such as `setup-node`, which has a problem matcher for eslint.

Alternatively, I could create a new action for the matcher. However, this would be less convenient.

**Comment by kiancross** [comment]
See: https://github.com/actions/setup-java/pull/198#issuecomment-886128475.
