### ISSUE TITLE
- nombre: Configurar Java JDK   usos: actions/setup-java@v2.2.0

### ISSUE THREAD

**Issue by Jhonnimil** [actions/setup-java#207]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @Jhonnimil. I'm closing the issue for now, because it looks like a spam. If you have any concerns feel free to feel the issue and reopen it.
