### ISSUE TITLE
Cannot specify a specific LTS ubuntu version

### ISSUE THREAD

**Issue by stephaniewang526** [actions/setup-java#216]
**Description:**
The googleapis Java client libraries are all impacted due to a recent update in `ubuntu-latest` which upgraded Maven version from `3.8.1` to `3.8.2`. We want to continue using the version of ubuntu (`20.04.02`) which is bringing mvn `3.8.1` but we are unable to. It [would use `ubuntu-latest`](https://github.com/googleapis/java-bigquery/pull/1556/checks?check_run_id=3499283310#step:1:7) even when we [set the version specifically to `ubuntu-20.04.02`](https://github.com/googleapis/java-bigquery/pull/1556/files#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR9) -- notice here that we want `20.04.02` but it's giving us `20.04.04`.

Could you let us know how we can pin the version to `20.04.02`? We currently decided to downgrade to `ubuntu-16.04` but we know that it will go away on 9/20/2021.

Please advise. Thank you!

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Comment by stephaniewang526** [comment]
cc @neenu1995 @chingor

**Comment by maxim-lobanov** [comment]
Hello @stephaniewang526 ,
It is not possible to specify exact image version. On Hosted runners, the latest version is always installed.

If you need to use previous version or freeze version, you can install it in runtime.
The easiest way is using community actions ([Link 1](https://github.com/marketplace/actions/setup-maven) and [Link 2](https://github.com/marketplace/actions/setup-maven-3))

**Comment by stephaniewang526** [comment]
Thanks for your fast response!

Can this be considered as a FR?

**Comment by dmitry-shibanov** [comment]
Hello @stephaniewang526. It can be considered as a FR.
For now I'm closing the issue. If you have any concerns feel free to ping us.
