### ISSUE TITLE
Does not seem to work with java-version 13

### ISSUE THREAD

**Issue by manastalukdar** [actions/setup-java#22]
With `java-version: "13"`:

```plaintext
Run actions/setup-java@v12s
##[error]Node run failed with exit code 1
Run actions/setup-java@v1
  with:
    java-version: 13
    architecture: x64
##[error]No valid download found for version 13.x. Check https://static.azul.com/zulu/bin/ for a list of valid versions or download your own jdk file and add the jdkFile argument
##[error]Node run failed with exit code 1
```

Looking at the https://static.azul.com/zulu/bin/ link, there is a jdk 13.  I tried the full sematic version (13.0.0, 13.0.3) thinking perhaps that is what the action script expects. But that did not work as well.

**Comment by giltene** [comment]
The Zulu CDN files have been updated now to include 13.0.0 in the name format setup-java expected to find (...jdk13.0.0..., not just ...jdk13...), and 13 now works. [Confirmed with e.g. https://github.com/HdrHistogram/HdrHistogram/blob/master/.github/workflows/maven.yml#L24 ]. I think we can close this bug.

**Comment by manastalukdar** [comment]
Yes, this now works. Closing issue.

**Comment by msgilligan** [comment]
I'm getting an "Unsupported class file major version 57" error when I try to run Gradle -- it works with 11 and 12:

```
Run ./gradlew -Ddownload.jpackage=true build bitcoinj-walletfx-template:jpackage --stacktrace
7
Downloading https://services.gradle.org/distributions/gradle-5.6.2-bin.zip
8
.........................................................................................
9

10
Welcome to Gradle 5.6.2!
11

12
Here are the highlights of this release:
13
 - Incremental Groovy compilation
14
 - Groovy compile avoidance
15
 - Test fixtures for Java projects
16
 - Manage plugin versions via settings script
17

18
For more details see https://docs.gradle.org/5.6.2/release-notes.html
19

20
Starting a Gradle Daemon (subsequent builds will be faster)
21

22
FAILURE: Build failed with an exception.
23

24
* What went wrong:
25
Could not open settings remapped class cache for eq4swfk4mzs03f3wxrd782ia1 (/home/runner/.gradle/caches/5.6.2/scripts-remapped/settings_7mnxgpzbq1ppapini4njtsssj/eq4swfk4mzs03f3wxrd782ia1/settings8410a2d21ed2f87c8a0398566330ee52).
26
> Could not open settings generic class cache for settings file '/home/runner/work/bitcoinj/bitcoinj/settings.gradle' (/home/runner/.gradle/caches/5.6.2/scripts/eq4swfk4mzs03f3wxrd782ia1/settings/settings8410a2d21ed2f87c8a0398566330ee52).
27
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57
28
```

**Comment by msgilligan** [comment]
@giltene Did you see the above? Any ideas what could be going wrong? My local build with the same `gradlew` and JDK 13 works fine.

**Comment by giltene** [comment]
Gradle 5.6.2 does not appear to support JDK13 (on its own) apparently. But will in Gradle 6.0. 
See https://github.com/gradle/gradle/issues/8681 

There are workarounds that involve keeping JDK 8 or 11 around to run gradle on. My guess is that your local setup is using JDK 8 to run gradle, and JDK 13 in the build process. But the CI workflow you use (linked to in you comment above) will only have 13 for JAVA_HOME.

A possible path forward without waiting/moving to the gradle (not yet released as 6.0) tip: You can *try* to use two separate steps of setup-java, one for 8 and one for 13, with a run step between them that will copy JAVA_HOME from the first step to e.g. GRADLE_JAVA_HOME, before the second setup-java step overrides it. You can then modify the gradlew script in your repo to use GRADLE_JAVA_HOME in its JAVACMD if it is set (e.g. duplicate the logic at https://github.com/ConsensusJ/bitcoinj/blob/consensusj-master/gradlew#L91 for a GRADLE_JAVA_HOME ahead of looking for JAVA_HOME).

**Comment by msgilligan** [comment]
> My guess is that your local setup is using JDK 8 to run gradle, and JDK 13 in the build process. 

No, it's definitely using JDK 13 and working correctly on my Mac, because the build prints the JDK version to the console. But "not supporting" JDK 13 doesn't necessarily mean that it won't work in some configurations, I guess. I'm not sure what the difference is.

**Comment by giltene** [comment]
The JDK the build uses (to compile and test) and the JDK gradle is running on can be different... But in any case, the error you are running into:
[looking deeper down you exception stack:]
207 Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57
208      at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
209      at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
210       at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
211        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)

is exactly the same as the one in https://github.com/gradle/gradle/issues/8681 , and it is caused by the groovy asm not knowing how to read Java 13-compiled classes (with a java 13 target). Not sure what combination is allowing it to work well on your desktop (maybe you end up with a newer version of groovy?, maybe the files groovy is looking to parse are built with a target lower than JDK 13?), but it's clear from the groovy issue link that you'll need groovy 6.0 (snapshots available but not yet released) to work well with JDK13.

**Comment by jamespedwards42** [comment]
@giltene Thanks for the two separate steps suggestion, worked like a charm: https://github.com/comodal/json-iterator/blob/master/.github/workflows/gradle.yml#L20

Relevant Gradle config needed: https://github.com/comodal/json-iterator/blob/master/systems.comodal.json_iterator/build.gradle#L196

CC @msgilligan
