### ISSUE TITLE
Not in gzip format

### ISSUE THREAD

**Issue by Alexander-Scott** [actions/setup-java#23]
Hi, I am getting an error when running the setup-java step in the following configuration:
```yaml
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
```

The error I get is the following:

```console
Run actions/setup-java@v1
/bin/tar xzC /home/runner/work/_temp/temp_1966052730 -f /home/runner/work/_temp/7c187b07-8201-4bf2-b87d-247013d1c81d

gzip: stdin: not in gzip format
/bin/tar: Child returned status 1
/bin/tar: Error is not recoverable: exiting now
##[error]The process '/bin/tar' failed with exit code 2
##[error]Node run failed with exit code 1
```

After doing some googling, [this](https://stackoverflow.com/questions/16381917/issues-uncompressing-a-tar-gz-file) looks to be the most relatable problem, but I notice it's not being downloaded the Oracle site, rather from this [site](https://cdn.azul.com/zulu/bin/) so I don't think cookies are the issue. Has anyone else also encountered this error?

**Comment by bijancn** [comment]
I also see this issue. Here for example https://github.com/starship/starship/pull/383/checks?check_run_id=240449201

**Comment by pzygielo** [comment]
Experiencing the same for `java-version: 1.8` as well.

**Comment by ray26** [comment]
I have got this error too in Java-version:1.8

**Comment by zhzy0077** [comment]
Having the same problem. It was fine several hours ago.

**Comment by ConorTheDev** [comment]
Also having this issue on my [repo](https://github.com/MediaModMC/MediaMod)

**Comment by joschi** [comment]
Same problem here with Java 1.8, 11, and 13.

dropwizard/dropwizard#2945

**Comment by amardeshbd** [comment]
Getting same error in 

* https://github.com/amardeshbd/android-barebone/commit/53ccf2935b70c4de9ef03a83faebd033d677bbad/checks
* https://github.com/amardeshbd/android-barebone/commit/bfa508fd067c00716b9eb2b400b5fd3165a34baa/checks

```
2019-09-29T13:48:22.8414796Z ##[group]Run actions/setup-java@v1
2019-09-29T13:48:22.8414968Z with:
2019-09-29T13:48:22.8415075Z   java-version: 1.8
2019-09-29T13:48:22.8415178Z   architecture: x64
2019-09-29T13:48:22.8415261Z ##[endgroup]
2019-09-29T13:48:25.3090327Z [command]/bin/tar xzC /home/runner/work/_temp/temp_1728142126 -f /home/runner/work/_temp/2cb0bc34-a362-42f1-9238-54ed8d5abeb1
2019-09-29T13:48:25.3150969Z 
2019-09-29T13:48:25.3151555Z gzip: stdin: not in gzip format
2019-09-29T13:48:25.3153719Z /bin/tar: Child returned status 1
2019-09-29T13:48:25.3154126Z /bin/tar: Error is not recoverable: exiting now
2019-09-29T13:48:25.3221359Z ##[error]The process '/bin/tar' failed with exit code 2
2019-09-29T13:48:25.3270890Z ##[error]Node run failed with exit code 1
```

**Comment by giltene** [comment]
Looks like some added .sig files (.tar.gz.sig) on the CDN were being confused for the .tar.gz files by installer.ts. The .sig files have been removed from the CDN for now, but are the tool-cache seems to have cached them.

**Comment by buckett** [comment]
@giltene I've just kicked off a build and the install worked correctly this time, thanks for the fix.

**Comment by giltene** [comment]
Looks like the caches for the .sig stuff have now expired and things work again for all versions (6,7,8,9,10,11,12,13). Will work on an installer.ts change and pull request to make sure .tar.gz is expected at end of filename (to ignore .tar.gz.sig) before we re-enable .sig files on the CDN.

**Comment by ray26** [comment]
It seems that the java 1.8 works fine with my project. Thanks for your fixing.

**Comment by joschi** [comment]
The [actions/setup-java](https://github.com/marketplace/actions/setup-java-action) GitHub Action seems to work again. 🎉

In case somebody is looking for a GitHub Action for setting up a Java development environment based on the [AdoptOpenJDK](https://adoptopenjdk.net/) OpenJDK distribution:
[joschi/setup-jdk](https://github.com/marketplace/actions/setup-java-environment-based-on-adoptopenjdk)

**Comment by JoeHegarty** [comment]
This has started to fail for us again today. Anyone else experiencing it?

**Comment by Scoppio** [comment]
Yes, I just had it this very minute, I was setting up Actions to allow for dependabot to work better, but it failed hard and I cant test my actions anymore.

**Comment by thuguerre** [comment]
I noticed the same kind of error on my workflow. all worked well yesterday

**Comment by jawher** [comment]
A workaround until this PR is merged is to use the @giltene's fork (cf. his PR to fix the issue: https://github.com/actions/setup-java/pull/24):

```yml
- name: Set up JDK 11
  uses: giltene/setup-java@master
  with:
    java-version: 11
```

**Comment by vinodkone** [comment]
yes, I'm seeing it in my project too.

**Comment by giltene** [comment]
Should be back to normal now.

This affected things that picked up "latest" (e.g. 8, 8.0.x, but not e.g. 8.0.222). Unfortunately, the new October 15 update releases posted earlier today for 7, 8, 11, and 13 all came with matching .sig  files. The new .sig files are now removed to prevent the problem with setup-java. Integrating the the PR (https://github.com/actions/setup-java/pull/24) will help avoid this sensitivity to non-jdk contents being posted to the cdn..

**Comment by thuguerre** [comment]
That's OK for me now. Thanks @giltene !

**Comment by joschi** [comment]
In case anyone is interested in using the OpenJDK distributions from [AdoptOpenJDK](https://adoptopenjdk.net/) instead of Azul's Zulu:
https://github.com/marketplace/actions/setup-java-environment-based-on-adoptopenjdk

**Comment by giltene** [comment]
@joschi there are quite a few OpenJDK distributions one can pick from, of which Zulu is one. There is plenty of choice, include the likes of Amazon’s Corretto, Bellsoft’s Liberica, Alibaba’s Dragonwell, and IBM’s AdoptOpenJDK. Of the set, Zulu happens to be the community OpenJDK distribution with the longest track record of delivering free, 100% OSS and consistently updated builds for OpenJDK 6,7,8,9,10,11,12, and 13, spanning back quite a few years. Older versions (like 7u181 or 8u131) may not seem “sexy”, but since CI and testing configs often freeze specific JDK versions to test against (usually in addition to testing on latest/greatest), a track record for prompt availability of new versions coupled with well maintained, long term stable archives of all builds across a wide version and date range is one of the key things driving the choice of OpenJDK distribution CI systems default to.

**Comment by joschi** [comment]
@giltene I don't want to start a big discussion here. I like Zulu and it served me well over the years, but people might want to use the AdoptOpenJDK distribution (not related to IBM), which is a bit clumsy to use with *this* GitHub Action.

More options, better ecosystem. 🎉

**Comment by konradpabjan** [comment]
PR #27 has gone in which had some small changes to prevent this error from happening again. 

Closing. If this happens in the future, either reopen this issue or create a new one.

**Comment by petermetz** [comment]
@konradpabjan It looks like the same issue has resurfaced just now: https://github.com/hyperledger/cactus/pull/978/checks?check_run_id=2635662049#step:2:19
(I think)
