### ISSUE TITLE
Support for monorepo

### ISSUE THREAD

**Issue by morki** [actions/setup-java#231]
**Description:**
Support for monorepo similar to [actions/setup-node](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies)'s  `cache-dependency-path`.

**Justification:**
Now it is unable to use `setup-java`'s Gradle caching (excellent!) with monorepo or simply with root project in another folder.  

**Are you willing to submit a PR?**
No, I don't understand the code and language of this repo.

**Comment by KengoTODA** [comment]
Current implementation satisfies the requirement, so we don't need additional configuration 🤗

Refer to the following code, it uses wildcard so it supports not only single module project but also monorepo.

https://github.com/actions/setup-java/blob/61c179a6ef8ea7bae7ab53f9e1e62ca9b1caebfa/src/cache.ts#L34

**Comment by morki** [comment]
Thank you for this information :)
