### ISSUE TITLE
Support for using URL in jdkFile

### ISSUE THREAD

**Issue by morki** [actions/setup-java#232]
**Description:**
It would be awesome to support URLs in addition to local paths for `jdkFile` input. 

**Justification:**
It should resolve all issues with custom Java distributions and versions and speed up builds by caching the downloaded result zip (key can be URL).

**Are you willing to submit a PR?**
No.

**Comment by Myoazwan95** [comment]
Duplicate of #88 
Duplicate of #233 
Duplicate of #1  #41

**Comment by IvanZosimov** [comment]
Hi, @morki 👋 We investigated your feature request thoroughly, but unfortunately we have to reject it because of the possible licenses and security issues associated with this feature.
