### ISSUE TITLE
Include version catalog file in filehash in the Gradle cache key

### ISSUE THREAD

**Issue by 3flex** [actions/setup-java#237]
**Description:**
Add `libs.versions.toml` or `*.versions.toml` to the cache key for Gradle dependency caching.

**Justification:**
[Central declaration of dependencies](https://docs.gradle.org/7.2/userguide/platforms.html#sub:central-declaration-of-dependencies) is an incubating Gradle feature that supports centralisation of configuration of dependencies & versions. By convention this is done in a file named `libs.versions.toml`: https://docs.gradle.org/7.2/userguide/platforms.html#sub:conventional-dependencies-toml

Projects that start using this feature can't practically use the Gradle caching feature in setup-java because the cache key will not change in most cases when dependencies are updated in the TOML file.

**Are you willing to submit a PR?**
~~Yes - if this change is acceptable.~~ Edit: no, as I will be using [gradle/gradle-build-action@v2](https://github.com/gradle/gradle-build-action) instead which I discovered after raising this issue.

**Comment by Montaserbdrelden25** [comment]
Thanks again and have fun 👍 تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: Matthew Haughton ***@***.***> التاريخ: ١٤‏/١٠‏/٢٠٢١  ٥:٠٦ ص  (GMT+02:00) إلى: actions/setup-java ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: Re: [actions/setup-java] Include version catalog file in filehash in the Gradle cache key (#237) 
Just as an FYI there's less need for this for me personally as I will use ***@***.*** which has more robust support for caching dependencies as well as other build outputs like Gradle's build & configuration caches.
