### ISSUE TITLE
Add support for Scala

### ISSUE THREAD

**Issue by zaoqi** [actions/setup-java#25]

**Comment by electrum** [comment]
It looks like Scala is already supported: https://github.com/actions/starter-workflows/blob/master/ci/scala.yml

**Comment by joshmgross** [comment]
Thanks @electrum 

@zaoqi please see the starter workflows for an example of using Scale with GitHub Actions 
https://github.com/actions/starter-workflows/blob/master/ci/scala.yml

**Comment by curtcox** [comment]
This issue was closed, but never fixed. Issue #266 is the currently open equivalent.
