### ISSUE TITLE
Update `@actions/cache` version to 1.0.

### ISSUE THREAD

**Issue by aparna-ravindra** [actions/setup-java#253]
**Description:**
The action depends on [`@actions/cache`](https://github.com/actions/setup-java/blob/ae26cabe43aaa84f8539613cdb171b33610fa704/package.json#L27). The latest version `1.0.8` is now available and it supports upto 10GB cache upload. 

**Justification:**
Support 10GB cache upload using the latest version `1.0.8` of [`@actions/cache` ](https://www.npmjs.com/package/@actions/cache)

**Are you willing to submit a PR?**
Yes

**Comment by aparna-ravindra** [comment]
PR merged - https://github.com/actions/setup-java/pull/254

**Comment by dmitry-shibanov** [comment]
Thank you for your pull request. The pull request was merged. I'm going to close the issue
