### ISSUE TITLE
Error: getCacheEntry failed: Cache service responded with 500

### ISSUE THREAD

**Issue by MartenM** [actions/setup-java#261]
**Description:**
I am currently attempting to set up the very basic Java workflow for my projects. However, it seems to go wrong somewhere. It has worked with other projects, but the new ones seem to fail.
Excuse me if this is totally my fault and something that could easily be resolved. I tried google and nothing seems to turn up.

**Task version:**
Latest, straight from the marketplace.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Not sure how to reproduce this with an empty repo, but it should be possible to checkout [this one](https://github.com/MartenM/ServerTutorialPlus/runs/4494876587)

**Expected behavior:**
Setup Java :)

**Actual behavior:**
```
Run actions/setup-java@v2
  with:
    java-version: 11
    distribution: adopt
    cache: maven
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
Resolved Java 11.0.11+9 from tool-cache
Setting Java 11.0.11+9 as the default

Java configuration:
  Distribution: adopt
  Version: 11.0.11+9
  Path: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64

Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Error: getCacheEntry failed: Cache service responded with 500
```

Well the error part is where it goes wrong. That seems obvious, not sure what the error means though. The full logs can be found [here](https://pipelines.actions.githubusercontent.com/u8LGFy3Pa3AVCE5qZ2ccylHGrfDcw8uficVybOzotVijKFRzWS/_apis/pipelines/1/runs/1/signedlogcontent/2?urlExpires=2021-12-11T22%3A13%3A43.5495234Z&urlSigningMethod=HMACV1&urlSignature=n0La1lEu2DeTX4QuGtGvSA%2FQ%2FxVxE67rGTP8wBkVn4o%3D).

**Comment by goeh** [comment]
Same error here with a new Java+Gradle (ubuntu-latest) workflow I created yesterday.
```
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
```

```
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Error: getCacheEntry failed: Cache service responded with 500
```

Related to https://github.com/actions/cache/issues/698

**Comment by MartenM** [comment]
Seems to be related to the cache indeed and not to setup-java itself.
Will keep an eye on the issue and keep this one open in case someone else bumps into the issue.

**Comment by MartenM** [comment]
Issue has been resolved by GitHub

**Comment by lfgcampos** [comment]
I don't like to comment on old issues but just wanted to let everyone knows it is happening again and the original issue was also 'revived'
https://github.com/actions/cache/issues/698#issuecomment-1153555265
