### ISSUE TITLE
Integrate sbt into `setup-java` or create a new one called `setup-sbt` for better support for self-hosted runners :rocket: 

### ISSUE THREAD

**Issue by dimisjim** [actions/setup-java#266]
**Description:**
Seems that, currently, sbt is part of the github-provided virtual environments, and not in `setup-java`

**Justification:**
Having sbt installed in the github.com-provided runners is a bit problematic for users of self-hosted runners as it causes false expectations for this `setup-java` action, given that sbt is actually something that needs java to function. Thus installation of it would make much more sense to happen in this action, or alternatively in another new one, called `setup-sbt` or `setup-scala` (actually, an action with this name already exists and depends on a not very stable project, called jabba, see https://github.com/olafurpg/setup-scala/issues/48 for more background on this)

I had previously opened: https://github.com/actions/starter-workflows/issues/1309 which I have now closed, to keep comms here exclusively.

Our current, in-house workaround is to use sdkman.io to install everything manually in our self-hosted runners.

**Are you willing to submit a PR?**
Yes

**Comment by joschi** [comment]
Why wouldn't you use https://github.com/dwijnand/sbt-extras for this, similar to how it is typically done in Gradle projects (using the Gradle wrapper script)?

**Comment by dimisjim** [comment]
We have already used a script, like the one you linked.

This issue refers to native github actions, but thanks for sharing anyway :+1:

**Comment by dmitry-shibanov** [comment]
Hello @dimisjim. Thank you for your report. We do not plan to add functionality in the setup-java action to install sbt. The main purpose of the setup-java action is to install java from available distributions. Could you please check existing actions for sbt ?

**Comment by guizmaii** [comment]
@dimisjim sbt has been added to the by-default-installed softwares of the latest OS versions supported in Github Actions (see https://github.com/actions/virtual-environments#available-environments for the OS versions):
- macOS 11 (which is `macos-latest`): https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#project-management
- Windows Server 2019 (which is `windows-latest`): https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#project-management
- Ubuntu 20.04 (which is `ubuntu-latest`): https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#project-management

**Comment by fmeriaux** [comment]
+1 

it would be interesting to integrate the sbt cache like mvn or gradle https://github.com/actions/cache/blob/main/examples.md#scala---sbt

**Comment by joschi** [comment]
@fmeriaux Go for it. 😉 
https://github.com/actions/setup-java/blob/f69f00b5e5324696b07f6b1c92f0470a6df00780/src/cache.ts#L23-L36

**Comment by fmeriaux** [comment]
> @fmeriaux Go for it. 😉
> 
> https://github.com/actions/setup-java/blob/f69f00b5e5324696b07f6b1c92f0470a6df00780/src/cache.ts#L23-L36

done https://github.com/actions/setup-java/pull/302

**Comment by laughedelic** [comment]
FYI: https://github.com/coursier/cache-action handles sbt cache (also Mill, Ammonite, and is highly configurable).

**Comment by dmitry-shibanov** [comment]
Hello everyone. The new version was released with sbt caching support.

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm going to close the issue because the new version with sbt caching support was released and the major tag was updated. If you have any concerns feel free to ping us.
