### ISSUE TITLE
Is gpg-argument  '--pinentry-mode loopback' still necessary?

### ISSUE THREAD

**Issue by HannesWell** [actions/setup-java#271]
**Description:**
The documentation of the `setup-java` action states that for the `maven-gpg-plugin`  the `gpgArguments` should be configured to be `--pinentry-mode loopback` in order to "to pick up the `gpg.passphrase` value defined in Maven `settings.xml`." and consequently avoid failures of the signing process (this was added with PR #122).

But I just set up a Maven build that includes GPG signing and succeeds even tough the `--pinentry-mode loopback` arguments in the `maven-gpg-plugin` are not set.

Therefore I wonder if these arguments are still necessary? Maybe due to updates to GPG or the version used in the GH runners or maybe there is some magic environment configuration in the GH runners themself? I'm neither very familiar with GPG nor with the GitHub Action runners, so I cannot tell.
I just noticed that it worked for me even for several builds without that configuration. Or have I just been lucky and could get the errors mentioned in the document in some day?

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Set up a usual Maven build that includes gpg signing, but without specifying the `--pinentry-mode loopback` arguments for the gpg-process like I did here:
https://github.com/axkr/symja_android_library/blob/master/symja_android_library/pom.xml
The GH-workflow used to perform the build is:
https://github.com/axkr/symja_android_library/blob/master/.github/workflows/maven-build-master-and-publish-snapshot.yml

**Expected behavior:**
Failure of the GPG signing process.

**Actual behavior:**
Signing completed successfully.

**Comment by dmitry-shibanov** [comment]
Hello @HannesWell. Thank you for your report. We'll investigate the issue.

**Comment by GreatDealsForU** [comment]
> Hello @HannesWell. Thank you for your report. We'll investigate the **issue.**    what if i dont remember a request that was made how can i know if hacker?

**Comment by e-korolevskii** [comment]
Hello everyone, sorry for that it takes so long. 

If you not set a `--pinentry-mode` it will use the default of the agent. Since GnuPG 2.1.12 release, the default mode is `–allow-loopback-pinentry`, so that is the reason why it`s work even if you not specify that argument.

For now I will close that issue, but if you have any additional questions - feel free to ask here or open a separated issue.
