### ISSUE TITLE
pefjsck

### ISSUE THREAD

**Issue by dlaprogramowlsk** [actions/setup-java#273]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by Donnadam** [comment]
8 am so sick of GitHub emails. Why is it my email is still on there I
unsubscribed months ago. You can't tell me I had anything to do with all
these new projects.
Unless you are stuffing around my set up?
***@***.*** ***@***.***>*
