### ISSUE TITLE
Specific java distribution - temurin 11 - is always being downloaded

### ISSUE THREAD

**Issue by lhsilva** [actions/setup-java#294]
**Description:**
I believe there's an issue with the caching of temurin 11 distribution, because it is downloaded in every run instead of using a cached version.

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Repro steps:**  
If I configure setup-java with temurin 17 or adopt 11, everything seems to work fine:

Config:
`- name: Set up JDK
	uses: actions/setup-java@v2
	with:
	  java-version: '17'
	  distribution: 'temurin'
	  cache: 'maven'`

Result:
Run actions/setup-java@v2
Resolved Java 17.0.2+8 from tool-cache
Setting Java 17.0.2+8 as the default`

Java configuration:
  Distribution: temurin
  Version: 17.0.2+8
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-8/x64

When I change the config to temurin 11 it is always downloaded:

Config:
`- name: Set up JDK
	uses: actions/setup-java@v2
	with:
	  java-version: '11'
	  distribution: 'temurin'
	  cache: 'maven'`

Result:
Trying to resolve the latest version from remote
Resolved latest version as 11.0.14+101
Trying to download...
Downloading Java 11.0.14+101 (Temurin-Hotspot) from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.14.1_1.tar.gz ...
Extracting Java archive...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/05b1560a-3c58-4d7f-8a36-62c86cabeb0c -f /home/runner/work/_temp/8b9bc60b-fcfd-4f16-b7a7-5c0becf19bcb
Java 11.0.14+101 was downloaded
Setting Java 11.0.14+101 as the default
Java configuration:
  Distribution: temurin
  Version: 11.0.14+101
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-101/x64

**Comment by devinrsmith** [comment]
I've noticed this too.

On a [previous version of the environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20220131.1/images/linux/Ubuntu2004-Readme.md), it was successfully resolving from the tool-cache:

```
Resolved Java 11.0.13+8 from tool-cache
Setting Java 11.0.13+8 as the default

Java configuration:
  Distribution: temurin
  Version: 11.0.13+8
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.13-8/x64
```

On the [current version of the environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20220220.1/images/linux/Ubuntu2004-Readme.md), it is downloading (although, the Java configuration section *seems* to imply it's still using `/opt/hostedtoolcache/...`?):

```
Trying to resolve the latest version from remote
Resolved latest version as 11.0.14+101
Trying to download...
Downloading Java 11.0.14+101 (Temurin-Hotspot) from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.14.1_1.tar.gz ...
Extracting Java archive...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/ee4fc4f0-64c6-4053-8fda-f798f4ec0b1f -f /home/runner/work/_temp/d40f02e7-2d19-4ea2-8847-4e722c14d039
Java 11.0.14+101 was downloaded
Setting Java 11.0.14+101 as the default

Java configuration:
  Distribution: temurin
  Version: 11.0.14+101
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-101/x64
```


Both using 'actions/setup-java@v2' (SHA:f0bb91606209742fe3ea40199be2f3ef195ecabf).

The only difference from the default configuration is one is using cache gradle, and the other maven - but I suspect it may be a version string issues of some sorts unrelated to the gradle/maven cache?

**Comment by MaksimZhukov** [comment]
Hello @lhsilva !
Thank you for the report! We are investigating the issue

**Comment by miketimofeev** [comment]
@lhsilva this should be fixed now.
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/48208649/159425160-0b967ce9-943b-48eb-b6f2-280161b0b548.png">
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by lhsilva** [comment]
Tried it and can confirm it is fixed. Thank you! :)
