### ISSUE TITLE
Microsoft OpenJDK 17 out of date

### ISSUE THREAD

**Issue by codylerum** [actions/setup-java#296]
appears that the Microsoft distribution is very manual and has not been updated for the 17.0.2 release

Is there a process in place to get that updated?

**Comment by codylerum** [comment]
I do wonder if this should be a supported distribution if it can't be automated.

https://docs.microsoft.com/en-us/java/openjdk/download

**Comment by karianna** [comment]
> I do wonder if this should be a supported distribution if it can't be automated.
> 
> https://docs.microsoft.com/en-us/java/openjdk/download

We are going to be adding an API in the not too distant future (we wrote Adoptium's API, so it's matter of co-opting that :-))

**Comment by d3r3kk** [comment]
We do have 'static' URLs that you can use in this instance, that always point to the latest of a specific JDK version.

For instance, https://aka.ms/download-jdk/microsoft-jdk-17-linux-x64.tar.gz will currently download our `microsoft-jdk-17.0.2.8.1-linux-x64` build, and https://aka.ms/download-jdk/microsoft-jdk-11-linux-x64.tar.gz will download our `microsoft-jdk-11.0.14.1_1-31205-linux-x64` build.

Will that help? (We will update those static URLs with each release).

**Comment by d3r3kk** [comment]
We do have 'static' URLs that you can use in this instance, that always point to the latest of a specific JDK version.

For instance, https://aka.ms/download-jdk/microsoft-jdk-17-linux-x64.tar.gz will currently download our `microsoft-jdk-17.0.2.8.1-linux-x64` build, and https://aka.ms/download-jdk/microsoft-jdk-11-linux-x64.tar.gz will download our `microsoft-jdk-11.0.14.1_1-31205-linux-x64` build.

Will that help? (We will update those static URLs with each release).

**Comment by brunoborges** [comment]
@codylerum any thoughts on @d3r3kk's comment?

Also, @gdams can you please change your PR accordingly?

**Comment by codylerum** [comment]
That would probably work perfectly.

**Comment by e-korolevskii** [comment]
Hi all!

In the latest release, we have updated the Microsoft OpenJDK version to 17.0.3.
I'm closing this issue for now, but if you have any additional questions, you can ask them here or open a new issue.
Have a nice day!
