### ISSUE TITLE
Add cache status output

### ISSUE THREAD

**Issue by sergey-s-betke** [actions/setup-java#306]
**Description:**
Please, add cache status output `cache-hit` (see https://github.com/actions/cache).

**Comment by TomBeckett** [comment]
I think this is coming, we're just waiting for merge: https://github.com/actions/setup-java/pull/275

**Comment by marko-zivic-93** [comment]
Hello @sergey-s-betke 
Thank you very much for your request!
We are considering your feature request and will review the PR very soon and inform you about it.
Thank you for your patience.

**Comment by dmitry-shibanov** [comment]
Hello everyone. The cache-hit output was added. For now I'm going to close the feature request. If you have any concerns feel free to ping us.
