### ISSUE TITLE
Caching support for GHES

### ISSUE THREAD

**Issue by tiwarishub** [actions/setup-java#307]
**Description:**
👋  Team,  we have recently added support for caching in GHES (target version 3.5). And we saw ``setup-java`` action is also using the Action cache service to cache dependency, based on user input, using the ``actions/cache`` package of actions/toolkit. Unlike other setup-* actions (like setup-node, setup-python), setup-java actions is not using any explicit condition for GHES (for example like in setup-python we have  https://github.com/actions/setup-python/blob/main/src/setup-python.ts#L14-L16) . So for setup-java, no change is required to enable its cache usage on GHES  but if you like to check the Action cache service presence before starting caching dependency you can add use this new ``isFeatureAvailable`` [function](https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts#L52)  present in ``@actions/toolkit 2.0.0``  to check the presence of Actions cache service. 
You can also refer to [this](https://github.com/actions/cache/blob/c31528629d55886d56018ef0e8d0da5986e4fe31/src/utils/actionUtils.ts#L79-L93)  change which we are doing for [actions/cache ](https://github.com/actions/cache/) action. 

Please let me know if you need more clarification.

**Comment by tiwarishub** [comment]
cc: @actions/actions-service  for visibility

**Comment by marko-zivic-93** [comment]
We added caching support for GHES.
Closing the issue thread.
