### ISSUE TITLE
Setup task doesn't seem to use proxy settings

### ISSUE THREAD

**Issue by PostRaphaelPerrin** [actions/setup-java#311]
**Description:**
Installation is not happening in uses: actions/setup-java@v2(3)

**Task version:**
v2 and v3

**Platform:**
- [x ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x ] Self-hosted

**Repro steps:**  
Simply add the step : 
  uses: actions/setup-java@v3

**Expected behavior:**
The installation of the tool

**Actual behavior:**
Run actions/setup-java@v2
Trying to resolve the latest version from remote
##[debug]Gathering available versions from 'https://api.adoptopenjdk.net/v3/assets/version/%5B1.0,100.0%5D?project=jdk&vendor=adoptopenjdk&heap_size=normal&sort_method=DEFAULT&sort_order=DESC&os=linux&architecture=x64&image_type=jdk&release_type=ga&jvm_impl=hotspot&page_size=20&page=0'
Error: unable to verify the first certificate

Url is open through corporate proxy, I tested it successfully from the runner cli.

**Comment by dmitry-shibanov** [comment]
Hello @PostRaphaelPerrin. Thank you for your report. We'll investigate the issue.

**Comment by bantl23** [comment]
Where in the runner did you set this?

I tried added that env .github/workflows/action.yml but that didn't work. I'm assuming its being set on the runner itself somewhere?
