### ISSUE TITLE
🪳

### ISSUE THREAD

**Issue by Checkmate43** [actions/setup-java#324]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @Checkmate43. I'm going to close the issue because it looks like spam.
