### ISSUE TITLE
Error: read ECONNRESET when Trying to resolve the latest version from remote

### ISSUE THREAD

**Issue by johnfilo-kmart** [actions/setup-java#328]
**Description:**
When trying to find the latest version of java to download, I get the error Error: read ECONNRESET. Runner is a self-hosted runner in AWS.

**Task version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Repro steps:**  
  deploy-test-data:
    needs: [set_variables]
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: aws-${{ needs.set_variables.outputs.aws_account_id }}-kmg  
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Compile the Project
        run: mvn -B package --file pom.xml

**Expected behavior:**
Expect that it finds the latest version from remote

**Actual behavior:**
Runner output is

Run actions/setup-java@v3
  with:
    distribution: temurin
    java-version: 11
    cache: maven
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
Trying to resolve the latest version from remote
Error: read ECONNRESET

**Comment by dmitry-shibanov** [comment]
Hello @johnfilo-kmart. Thank you for your report. How often does this error appear ?

**Comment by johnfilo-kmart** [comment]
Hey @dmitry-shibanov every time I have tried so far. Our self-hosted runners sit behind a corporate proxy that may be blocking the https request being made here, so it would be really useful to know what URL the action is trying to access and I can attempt to connect directly to this URL from the runner itself and see if that is what is blocking the request?

**Comment by dmitry-shibanov** [comment]
Hello @johnfilo-kmart. Sorry for the late response. You can try to use this [URL](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.15_10.tar.gz).

**Comment by dmitry-shibanov** [comment]
Hello @johnfilo-kmart, just a gentle ping.

**Comment by dmitry-shibanov** [comment]
Hello @johnfilo-kmart. For now I'm going to close the issue. If you have any updates feel free to ping us.

**Comment by sammcj** [comment]
Hey, Sorry John didn't notice the notification of reply, we just noticed this again today with another project, using the URL provided above it does work, perhaps the Action needs some error handling or retry logic?
