### ISSUE TITLE
Allow to define a JAVA_HOME variable for each installation

### ISSUE THREAD

**Issue by laeubi** [actions/setup-java#337]
**Description:**

We have a setup where we need different JVM versions in `parallel`, for that we call the setup step multiple times and setup later a toolchain using the env variables. This works fine for Java 11 / 17 but with java 18 it produces a JAVA_HOME_**8**_X64 instead of JAVA_HOME_**18**_X64

**Task version:**
`v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
You can find a run here: https://github.com/eclipse/tycho/runs/6737378073
If you open the "Build Tycho" step, there is a list of env variables and one can see the following ones:

**Expected behavior:**
I want to see an env variable named `JAVA_HOME_18_X64`

**Actual behavior:**
I see an env variable `JAVA_HOME_8_X64` is created instead

**Comment by dmitry-shibanov** [comment]
Hello @laeubi. Thank you for your report. The action does not produce such kind of env variable. It produces only `JAVA_HOME`.

**Comment by laeubi** [comment]
@dmitry-shibanov so who is setting the variable then? I can only tell that adding this action makes both variables aviable `JAVA_HOME` and `JAVA_HOME_<version>_<arch>`.

**Comment by laeubi** [comment]
By the way this was mentioned here:
- https://github.com/actions/setup-java/issues/44#issuecomment-577232453

**Comment by dmitry-shibanov** [comment]
@laeubi I've [printed env variables](https://github.com/dmitry-shibanov/testActionTasks/runs/6739358483?check_suite_focus=true) by pattern `JAVA_HOME*`. Only the JAVA_HOME env variable is changed.

**Comment by laeubi** [comment]
@dmitry-shibanov first this is what I mean:

![grafik](https://user-images.githubusercontent.com/1331477/172016525-f1757356-6912-42aa-952b-bb90f0144b8b.png)

so somehow it *is* added but I have no idea why (maybe as result of tool install?) :-)

> Only the JAVA_HOME env variable is changed.

Maybe the action can then be changed to explicitly set those variables? This is incredible useful for such purposes where one needs many JVMs in the same run...

**Comment by dmitry-shibanov** [comment]
@laeubi The JAVA_HOME_* env variables are created during image generation [here](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/java-tools.sh#L36-L37). The action does not modify them.

**Comment by laeubi** [comment]
It seems in (older) versions of the script, they where also produced (or overridden) by the setup action:

https://github.com/actions/setup-java/blob/b52cd69bd2c048f71381fd0ee11739418a05a362/src/installer.ts#L76-L79

do you think such a feature could be added back? Maybe even by make the env variable configurable and defaulting to `JAVA_HOME`?

**Comment by laeubi** [comment]
Duplicate of #44
