### ISSUE TITLE
Azul Java 18 diappeared on Jun 7, between 4:34 PM CET+2 ... 4:48 PM CET+2

### ISSUE THREAD

**Issue by snazy** [actions/setup-java#338]
**Description:**

It seems that Azul Java 18 just "disappeared".
A GH workflow run for [this PR](https://github.com/projectnessie/cel-java/pull/195/commits/9b43013b58bf48af03783a9909e7f7bdb668e6a7) worked fine and could run against Java 18, but the actual [merged commit](https://github.com/projectnessie/cel-java/commit/c54522d9bc0f5650f1f31982637e575c938513d0) failed to run, complaining that there's no Java 18.

We have a WF running for PRs that automatically approve and merge PRs that passed CI, so we can narrow down the time when Azul Java 18 "disappeared" to sometime **between Jun 7 4:34 PM CET+2 ... 4:48 PM CET+2**.

Link to [failed WF](https://github.com/projectnessie/cel-java/runs/6777468022?check_suite_focus=true) run

**Task version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
?

**Expected behavior:**
Have Azul Java 18 back.

**Actual behavior:**
No Azul Java 18

**Comment by e-korolevskii** [comment]
Hello @snazy,

Thanks for your report! Unfortunately, the problem occurs on the _Azul_ side. Setup-Java uses _Azul_`s public API to get a list of available versions. We will continue to monitor the situation and explore possible solutions.

**Comment by dmitry-shibanov** [comment]
Hello @snazy. It looks like Azul Java 18 is available now. Could you please confirm that everything works as expected ?
