### ISSUE TITLE
Question/Bug a way to kill the JVM task after completion of said task?

### ISSUE THREAD

**Issue by Speiger** [actions/setup-java#349]
**Description:**
This is more of a question.
I have a big project running in github actions [Primitive Collections](https://github.com/Speiger/Primitive-Collections)
And building the project and running unit tests takes 3GB + 1GB of Ram, which sadly once it is done not released.
When the Python Script that builds a UnitTest statistics then runs through it only has 3GB instead of 7GB left.
Which causes it to fail because running out of ram due to the limited ram. So i am forced to do a reduced version
My question is how can i make that the JVM is killed after the task is done and the Ram is released afterwards.
This is the [Script](https://github.com/Speiger/Primitive-Collections/blob/master/.github/workflows/build_tests_action.yml) that I am running.
Thank you for reading.

**Task version:**
Java 11

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

**Expected behavior:**

**Actual behavior:**

**Comment by marko-zivic-93** [comment]
Hello @Speiger we will investigate this issue and come back to you as soon as we have some information regarding this issue :)

**Comment by Speiger** [comment]
I will try that ASAP, but don't have time right now. I will come back with info the moment I have tested that.
Thanks :)

**Comment by Speiger** [comment]
ok started the task.
https://github.com/Speiger/Primitive-Collections/runs/7160029336?check_suite_focus=true

**Comment by Speiger** [comment]
@dsame this didn't help as the Python script printed this.
2022-07-02 06:40:44 +0000 - publish -  INFO - Reading build/test-results/**/*.xml (7 266 files, 3.0 GiB)
After I edited the script to include that.

**Comment by Speiger** [comment]
Ok eh I have a crazy idea... But i would need a script that works accross Ubuntu/Windows/Mac.
A command that would kill all jvm tasks as a command. So i can run my commands then run the kill jvm command and then run the other scripts.

**Comment by dsame** [comment]
@Speiger 

all-platform solutions is to change your step to

```
      -  name: Build and Test
         run: |
           ./gradlew generateTestSource test jacocoTestReport --info -Dfull_test_suite=true
           ./gradlew --stop
```

This [effectively kills the java processes](https://github.com/akv-platform/Primitive-Collections/runs/7184186936?check_suite_focus=true) launched by gradle.

note: you do not need `--no-daemon` option

**Comment by Speiger** [comment]
Ok I ran your fix and it sadly didn't work.

Here is the task that failed with your suggested fix
https://github.com/Speiger/Primitive-Collections/runs/7186284341?check_suite_focus=true

Here is the check task that proofs that the script afterwards isn't memory bound to 3GB and shows that it doesn't work for whatever reason.
https://github.com/Speiger/Primitive-Collections/runs/7186754115?check_suite_focus=true

I am going to google foo a bit too to maybe find a solution.

**Comment by dsame** [comment]
Hello @Speiger ,

The last line of "Build and Test" steps now clearly says 
```
Stopping Daemon(s)
1 Daemon stopped
```
And it means the memory consumed by java process to be freed. 

Moreover the script you've mentioned before prints there's enough memory to read the xml files
```
2022-07-02 06:40:44 +0000 - publish -  INFO - Reading build/test-results/**/*.xml (7 266 files, 3.0 GiB)
2022-07-02 06:40:44 +0000 - publish -  INFO - Available memory to read files: 5.9 GiB
```

If you sure the next step failed because of lack of memory please try to add `sleep 10` shell step before the `Publish Test result steps`, but from the existing log i see a little hope it will help. 

I'd create an issue in this project https://github.com/EnricoMi/publish-unit-test-result-action to ask for more debug info and discovering the reason why it fails. Do you want me to create this issue and ask the question in your behalf?

**Comment by Speiger** [comment]
Yeah I am aware that it does it. I am going to try and add like a 1-2 second wait time to add it.
Also because i saw that it showed that i added a custom script making sure that the issue isn't on the Publish Test result action because if it was limited to 3GB only I would have not come back here and went to him.

About the issue:
https://github.com/EnricoMi/publish-unit-test-result-action/issues/304

I am already like 1 step ahead of you. Before this It actually didn't provide any info at all.
And as you see it is due to running out of memory, and he says since it is running within python it might not be really detectable.

But yeah you can open an issue and ask for info what you need and just ping me in there.

My guess is that either the test result amount is just so large that it requires just a very big amount of memory.
(it is the reason why it is like 7 gradle tasks instead of 1 for testing things)
Or the code is not optimized for keeping memory usage down.

I am betting on the first one though.

**Comment by dsame** [comment]
@Speiger 
if it is memory issue than that memory is limited not by the memory available for the build, but the memory allowed to the docker: https://github.com/Speiger/Primitive-Collections/runs/7186284341?check_suite_focus=true#step:8:22

Referencing https://github.com/EnricoMi/publish-unit-test-result-action project i supposed to add `--memory` option to docker cli:

https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

**Comment by Speiger** [comment]
Yeah the stop command actually gives it 5.9GB (6GB) of ram now that the delay was added.
https://github.com/Speiger/Primitive-Collections/runs/7214885381?check_suite_focus=true

But I am closing this one because at this point this isn't a problem of this action anymore and more a issue of the other plugin.

If you need 6GB of ram to complete a task of like 10 million test units then clearly the current implementation of the script isn't suited for the scale.

Anyhow thank you for the help you went beyond what was expected of you ^^"

**Comment by dsame** [comment]
@Speiger thank you for closing the issue, but i want to stress the fact the publish action runs within a docker container and that container has its own memory limitation, i am 80% sure that's is the reason. Despite any memory consumption the action should work until it is cancelled because of a timeout in the worst case.

**Comment by Speiger** [comment]
No problem, and yes i am aware. To be honest i think the action just needs a optimization to deal with larger scale tests, in worst case like move data to the disk while that slows it down a bit, speed isn't like something people care about at such a scale.
That is at least I would do, divide it into split amounts and slowly merge them together once everything is processed.
