### ISSUE TITLE
FindJNI.cmake not finding JNI after this setup completes.

### ISSUE THREAD

**Issue by MarkCallow** [actions/setup-java#372]
**Description:**
After running this setup a cmake config with a CMakeLists.txt that includes

```
find_package(JNI 11 REQUIRED COMPONENTS Development)
```

fails with the message

```
Could NOT find JNI (missing: Development) (Required is at least version "11")
```

**Task version:**
v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:** 

Use this setup as follows

```
    - name: Set up JDK 17.
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
```

then have a subsequent build step
```
    - name: Build Windows
      run: |
        echo "JAVA_HOME=$env:JAVA_HOME"
        ci_scripts/build_win.ps1
```

The echo is for debugging. JAVA_HOME appears set correctly to

```
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\17.0.4-8\x64
```

The build script should do an e.g, `cmake . -G "Visual Studio 16 2019" -B <build dir>` where the CMakeLists.txt contains

```
find_package(JNI 11 REQUIRED COMPONENTS Development)
```

**Expected behavior:**
I expected JNI Development to be found.

This find_package has worked on Appveyor CI and on my Windows systems.

**Actual behavior:**
The config step fails with the message

```
Could NOT find JNI (missing: Development) (Required is at least version "11")
```

**Comment by dmitry-shibanov** [comment]
Hello @MarkCallow. Thank you for your report. Could you please provide a link to the public repository to reproduce the issue.

**Comment by MarkCallow** [comment]
> Could you please provide a link to the public repository to reproduce the issue.

The repo/branch is 

https://github.com/KhronosGroup/KTX-Software/tree/rm_vs2015

Here's the log from a failed run:

https://github.com/KhronosGroup/KTX-Software/runs/7930361857?check_suite_focus=true

**Comment by MarkCallow** [comment]
I attempted to debug this issue by copying `FindJNI.cmake` to my project's `modules` directory and editing it to print some debug messages. Unfortunately CMake then attempts to find the modules it includes in my project's `modules` directory. (Ultimately many modules are used and it isn't practical to copy all of them to my project's `modules` directory.) This is because the includes are of the form

```
include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
```

and I can't find any variable that refers to CMake's built-in modules directory with which to replace `CMAKE_CURRENT_LIST_DIR`. Any tips gratefully received.

**Comment by MarkCallow** [comment]
When WIN32 is set `FindJNI`does

```
execute_process(COMMAND REG QUERY HKLM\\SOFTWARE\\JavaSoft\\JDK
   ...
)
```

even when `JAVA_HOME` is set. Does Temurin make such a registry entry?

T.B.H I don't fully understand what FindJNI is doing especially why is does this query even if _JAVA_HOME is set.

**Comment by MarkCallow** [comment]
> ... just to check, did you check this issue? #341

No I hadn't. Given its title, I can see why my search, before opening this issue, failed to find it.

In my case `JAVA_HOME` is being set by `setup-java` so if it is wrong, it is a bug in setup-java.

> even if `_JAVA_HOME` is set.

To avoid any confusion from my earlier comment, `_JAVA_HOME` is an internal variable in `FindJNI.cmake` which is set from `JAVA_HOME`, if that is set.

**Comment by MarkCallow** [comment]
This problem resulted from my having `COMPONENTS Development` at the end of my `FindJNI` command. This was left over from a long time ago when I was at first using `FindJava`. It seems there must have been a change in `FindJNI` in CMake 3.24 as it works fine with Temurin with `COMPONENTS` included in all the cmakes I've been using including 3.23.1.

To answer one of my other questions in case it helps others. Temurin makes a registry entry but it is different from the one being sought by `FindJNI`, at least prior to CMake 3.24. `FindJNI` looks for `HKLM\Software\JavaSoft\JDK` while Temurin's is `HKLM\Software\Eclipse Temurin\JDK`. When the query fails, `FindJNI` uses `_JAVA_HOME`. If the query succeeds, the result will override `_JAVA_HOME`.
