### ISSUE TITLE
Huncho Nation 

### ISSUE THREAD

**Issue by Hunchomilly** [actions/setup-java#378]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by Hunchomilly** [comment]
Keep streaming and supporting God bless you

**Comment by panticmilos** [comment]
hi @Hunchomilly, since it's looking like a spam I am going to close the issue :)
