### ISSUE TITLE
Error: No file in /home/runner/work/my-iac-sdk/my-iac-sdk matched

### ISSUE THREAD

**Issue by batmakur** [actions/setup-java#381]
**Description:**
Error: No file in /home/runner/work/my-iac-sdk/my-iac-sdk matched to [**/*.gradle*,**/gradle-wrapper.properties,buildSrc/**/Versions.kt,buildSrc/**/Dependencies.kt], make sure you have checked out the target repository
**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
Added java setup sets in Github action pipeline 
- name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{matrix.javaversion}}
**Expected behavior:**
Java configuration:
    Distribution: temurin
    Version: 11.0.16+1
    Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-1/x64
  
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Received 3786482 of 3786482 (100.0%), 26.0 MBs/sec
Cache Size: ~4 MB (3786482 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e3588fe9-5bdd-4298-9766-0b38b804e824/cache.tzst -P -C /home/runner/work/my-kubernetes/my-kubernetes

**Actual behavior:**

Error: No file in /home/runner/work/pulumi-iac-sdk/pulumi-iac-sdk matched to [**/*.gradle*,**/gradle-wrapper.properties,buildSrc/**/Versions.kt,buildSrc/**/Dependencies.kt], make sure you have checked out the target repository

**Comment by dmitry-shibanov** [comment]
Hello @batmakur. Thank you for your report. Could you please provide a public repository to reproduce the issue ?

**Comment by bala-auvaria** [comment]
Hi, Unfortunately I am working on the private repo.

**Comment by dmitry-shibanov** [comment]
Hello @bala-auvaria. Could you please try to reproduce the issue on simple public repository ? I've tried to reproduce it on simple project but it looks like everything works as expected.

**Comment by dmitry-shibanov** [comment]
Hello @bala-auvaria, just a gentle ping.

**Comment by panticmilos** [comment]
hi @bala-auvaria, I will close this issue because of the inactivity. Feel free to reopen it :)

**Comment by gigaSproule** [comment]
In case anyone else comes across this, I hit this because we have a composite action that wraps around this, defaulting to 'gradle', but a workflow we have needs that composite action, but doesn't have any build platform with cacheable dependencies. Rather than just ignoring the missing files, this action seems to check to ensure cacheable files exist first.

This isn't a complaint, as why would you specify a caching mechanism when you don't have anything to cache, just something worth being aware of.
