### ISSUE TITLE
Support Java 19 (Temurin)

### ISSUE THREAD

**Issue by Harmelodic** [actions/setup-java#388]
**Description:**
Support setting up Java 19 (specifically with Temurin)

**Justification:**
I'd like to build and run my application using JDK 19, and use the Temurin JDK to do so.

**Comment by dmitry-shibanov** [comment]
Hello @Harmelodic. Thank you for your feature request. The Java Temurin 19 will be automatically available through action and API when it's released. For now you can check status [here](https://github.com/adoptium/adoptium/issues/171).
