### ISSUE TITLE
JAVA_HOME is not set correctly on MacOS for local (jdkFile) installed JDKs that are present in the tool cache

### ISSUE THREAD

**Issue by erwin1** [actions/setup-java#396]
**Description:**
Local installed JDKs using the jdkFile option that are already present in the tool cache are not checked for suffix 'Contents/Home' on macos, so as a result the JAVA_HOME is not set correctly.

**Task version:**
v3

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
- run a workflow with setup-java with a jdkFile option on a self-hosted runner on MacOS using a JDK that places files in 'Contents/Home'
- the first time this works fine. JAVA_HOME is set correctly including 'Contents/Home'
- run the workflow again, this time the JDK will already be present in the tool cache
- setup-java now sets JAVA_HOME without the 'Contents/Home' suffix

**Expected behavior:**
When the JDK is available in the tool cache, JAVA_HOME must be set correctly.

**Actual behavior:**
When the JDK is available in the tool cache, JAVA_HOME is set without checking if the JDK is placed in 'Contents/Home'

**Comment by panticmilos** [comment]
hi @erwin1, thank you for the report. We will take a look at it

**Comment by panticmilos** [comment]
By the way, could you provide us public repo with repro steps?

**Comment by erwin1** [comment]
Thanks.

Here's a public repo: https://github.com/erwin1/setup-java-mac-sscce 
On a hosted runner it's a bit harder to reproduce because every run happens on a different runner (without tool cache).

Although I was able to reproduce with a trick to use setup-java again in the same action.

This fails:
https://github.com/erwin1/setup-java-mac-sscce/actions/runs/3344915283/jobs/5539822614

And using the proposed fix from #397 it works:
https://github.com/erwin1/setup-java-mac-sscce/actions/runs/3344942099/jobs/5539881412

**Comment by erwin1** [comment]
added 2 unit tests of which one fails (`java is resolved from toolcache including Contents/Home on MacOS`) without the proposed fix

**Comment by erwin1** [comment]
Any chance we can move this forward?

**Comment by panticmilos** [comment]
hi @erwin1, sorry for the delayed answer, thank you for the repo I will take a look again :)

**Comment by erwin1** [comment]
We are still regularly running into this issue, so it would be great to get a review on the PR. Thanks!

**Comment by dmitry-shibanov** [comment]
Hello @erwin1. We've merged your pull request. For now you can try to use this changes with `actions/setup-java@main`. We'll ping you when new release is ready. 

For now I'm going to reopen it until we release a new version.

**Comment by erwin1** [comment]
Thanks, using `@main` works as expected now:
https://github.com/erwin1/setup-java-mac-sscce/actions/runs/4606608821

**Comment by IvanZosimov** [comment]
Hi, @erwin1  👋 The [new version](https://github.com/actions/setup-java/releases/tag/v3.12.0) of the setup-java is released. Please, check it out.

I'm going to close this issue, If you have any additions or questions feel free to ping us.
