### ISSUE TITLE
Support JetBrainsRuntime distribution

### ISSUE THREAD

**Issue by Syer10** [actions/setup-java#399]
**Description:**
Add support for JetBrainsRuntime Java distribution https://github.com/JetBrains/JetBrainsRuntime/

**Justification:**
I build a desktop app using Compose Multiplatform, and the best distribution to use when building/packaging it is JetBrains Runtime because it expands the runtime support for GUI apps, expanding Swing and AWT support for every platform and fixing bugs. I use Github Actions to build my app so having it be supported in this action would be very helpful.

**Are you willing to submit a PR?**
Im not familair with TypeScript/JavaScript so I cannot say yes.

**Comment by marko-zivic-93** [comment]
Hello @Syer10

**Comment by panticmilos** [comment]
hi @Syer10, after the consultation with the team we have decided we are not currently planning to implement this feature. But I will not close this issue, because we want to see how much attention it is going to get :)

**Comment by yeikel** [comment]
@panticmilos Would you accept community contributions for this? If so, feel free to assign this to me

**Comment by jsoref** [comment]
It doesn't seem like they'd accept a community contribution without first showing demand.

But you could make a fork that included it and the evidence of repositories using your fork would be a good way to convince them to integrate it.

**Comment by panticmilos** [comment]
hi @yeikel, sorry for the delayed response. We are still not going to close this feature request, but still keeping it open for same reasons that I mentioned in the comment above :)

**Comment by nicbell** [comment]
This sounds like a good idea especially for Android projects as it will match Android Studio.

**Comment by SingingBush** [comment]
I'd certainly like setup-java to support **jbr** as a distribution. It's worth doing for people that produce plugins for Jetbrains IDE's.

**Comment by jsoref** [comment]
@yeikel why not create a branch in your fork that adds the support and then link to it here. We'll be able to see how much your repository is used pretty easily (GitHub tracks dependencies).

**Comment by yeikel** [comment]
> @yeikel why not create a branch in your fork that adds the support and then link to it here. We'll be able to see how much your repository is used pretty easily (GitHub tracks dependencies). 

My intention was to contribute to this project in general, and I saw an issue I could try

I have no particular interest or need to support this runtime, and maintaining a fork is not something I am interested at this time

**Comment by Pogie10** [comment]
hOY MGA PUTANG INA NYO ANU PINAG KAJAGULUHAN NYO MGA HINDOT KAU

**Comment by MessiasLima** [comment]
Would be nice to have thin in GitHub actions

**Comment by gmitch215** [comment]
This is a little late, but I [submitted a PR](https://github.com/actions/setup-java/pull/637) that adds support for this:

```yml
- name: Setup JBR 17
  uses: gmitch215/setup-java@e1f4c15facc0cf68c0e764340e374be034e4a859
  with:
    distribution: 'jetbrains'
    java-version: 17
```

**Comment by apolostudio** [comment]
any news on this?

**Comment by gmitch215** [comment]
See #637
