### ISSUE TITLE
Allow to customize Maven version

### ISSUE THREAD

**Issue by kwin** [actions/setup-java#40]
It should be possible to set a specific Maven version to use with `mvn`. For that it should be optionally possible to download also Maven from some Apache mirror (https://maven.apache.org/download.cgi) after downloading Java and then use that mvn version.

**Comment by giltene** [comment]
+1

While this seems like feature creep, I agree that it would be useful to specify versions for both maven and gradle. This is especially useful for using EA and RC versions (e.g. Gradle support JDK 13 arrived ~2 months after JDK 13, but gradle 6.0 release candidates were available). For ease of use, specifying a version would be a good first option via e.g. gradleVersion or mvnVersion (which would then choose from a well known curated source for either maven or gradle), and supplying a URI or a file should certainly be an option (similar to the jdkFile option).

**Comment by jvalkeal** [comment]
I had some code for this so created a PR. We'll see what maintainers think about it.

**Comment by giltene** [comment]
Very cool! And I think the spelling you chose (e.g. maven-version, gradle-version) fits cleanly and naturally with the existing java-version spelling.
👍

**Comment by martinpaljak** [comment]
Would love to see this being available!

**Comment by brunoborges** [comment]
I think Maven and/or Gradle support should be provided in separate actions.

**Comment by joschi** [comment]
@kwin @giltene Why not use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) or [Maven wrapper](https://github.com/takari/maven-wrapper) instead?

That way you can build the project locally and aren't depending on the GitHub action to set up everything for you.

**Comment by garydgregory** [comment]
> @kwin @giltene Why not use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) or [Maven wrapper](https://github.com/takari/maven-wrapper) instead?
> 
> That way you can build the project locally and aren't depending on the GitHub action to set up everything for you.

Over at Apache Commons we have 30 Components, each it's own Maven build in it's own repository, and I would not want to duplicate these wrapper files all over the place. It seems to me that a maven setup action is the most modular and flexible.

**Comment by brunoborges** [comment]
@garydgregory our recommendation is that developers use a separate Action for Maven. There are a few options already available on the Marketplace [1].

[1] https://github.com/marketplace?type=actions&query=maven

**Comment by garydgregory** [comment]
Thank you!

**Comment by famod** [comment]
Heads up:
In case anyone is using https://github.com/stCarolas/setup-maven, you will most likely run into `M2_HOME` env var being set although it not used by newer Maven versions anymore: https://github.com/actions/virtual-environments/issues/2534

@joschi 
> Why not use the Gradle wrapper or Maven wrapper instead?

For instance, compatibility tests require different versions in CI.
I'm maintaining a Maven extension (https://github.com/vackosar/gitflow-incremental-builder) and I need to also check that nothing breaks with older Maven versions.
Maven wrapper does not seem to be right choice for this.

**Comment by cesarhernandezgt** [comment]
Hi @brunoborges @maxim-lobanov 

> I think Maven and/or Gradle support should be provided in separate actions.

This was useful in Apache-related projects, now since early 2021 the usage of non-verified actions is discouraged, and that basically leaves an empty result set when you want to search for Maven verified Actions. 
https://github.com/marketplace?query=maven&type=actions&verification=verified

I see this issue labels moved from `enhancement` into `feature request` which makes me think we are far from seeing the solution implemented (I hope I'm wrong in the label understanding).

What is the process to "certified" or "verify" an action? or what other alternatives do we currently have to try setting specific maven version for multi-branch projects?

**Comment by maxim-lobanov** [comment]
Hello @cesarhernandezgt , we don't have plans to include Maven support to this action. We would like to keep functionality of this action limited to Java installation / switching.
The another reason is that we don't have enough experience with Maven to maintain and support action for this tool.

Ideally, we would expect Maven team to develop official action for GitHub Actions to support Maven. In this case, customers will get expert support of their builds. Just an examples: [Ruby](https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby), [Setup Terraform](https://github.com/marketplace/actions/hashicorp-setup-terraform), [Azure CLI Action](https://github.com/marketplace/actions/azure-cli-action).

As for the verifying actions - https://github.community/t/how-to-become-verified-creator-of-a-github-action/116009. As far as I know, tool owner can get `verified` label on own actions.

**Comment by cesarhernandezgt** [comment]
Thanks for the replied @maxim-lobanov 

I started an email thread in the maven community dev mailing list [1] to get's more feedback on this topic. I'm eager to contribute since the number of non-verified maven actions beyond the scope mentioned in this ticket indicates that the end-users are needing these types of actions. 

[1] https://lists.apache.org/thread.html/r4b3723dfbf16cf86dd5765122adf3d836a4fc47585fdd9f79aab6e81%40%3Cdev.maven.apache.org%3E

**Comment by brunoborges** [comment]
@cesarhernandezgt I'd be curious to first learn what is really the use case, considering that the adoption of Maven Wrapper is increasing.

What should the Maven Action do that the Maven Wrapper script would not do?

**Comment by brunoborges** [comment]
I'd echo @maxim-lobanov's comment that Setup Java has no goal to include support for Maven/Gradle. Maxim, perhaps we should close this issue?

**Comment by cesarhernandezgt** [comment]
Also from the maven mailing list exchange, I found that sdkman has already an action: https://github.com/sdkman/sdkman-action but currently is not listed yet on the market. As for the context, it seems the verification for this action is not far away since it's coming from the official sdkman github organization.

**Comment by maxim-lobanov** [comment]
Thank you for discussion and your actions in this direction. As I mentioned above, there shouldn't be a problem to get verification for official action and we definitely encourage and can assist with it.
I am going to close the current issue.

**Comment by obfischer** [comment]
I would like to bring this issue up again, as this is a feature I would like to use in my setup. I don't want just to have build with different JDK versions, but also with more than one Maven version.

Please consider again to allow users of this action to choose the Maven version to use for the build. This feature will be required at least with the release of Maven 4.

**Comment by brunoborges** [comment]
I'm personally not in favor of this action having any further functionality other than setting up Java (the JDK, to be more specific).

Frankly, if this action ever gets a v3, it should not carry and feature that is not related to this particular goal.

An Action specifically for Maven should be born, for clear separation of concerns.

Plus, with composite actions now, I'd say this would be ideal.

**Comment by joschi** [comment]
> Please consider again to allow users of this action to choose the Maven version to use for the build. This feature will be required at least with the release of Maven 4.

The Maven Wrapper exists, now even as an official plugin: https://maven.apache.org/wrapper/maven-wrapper-plugin/

If your build relies on a specific version of Maven, then you should express that in your repository with the Maven wrapper downloading the exact version you need.

As an alternative, there are multiple actions on the marketplace which allow setting up Maven in GitHub Actions workflows:
https://github.com/marketplace?type=actions&query=maven

**Comment by obfischer** [comment]
> The Maven Wrapper exists, now even as an official plugin: https://maven.apache.org/wrapper/maven-wrapper-plugin/

In my case the Maven wrapper will not help, as I have to test my stuff with various Maven versions to detect incompatibilities in my software between Maven versions.
 
> As an alternative, there are multiple actions on the marketplace which allow setting up Maven in GitHub Actions workflows: https://github.com/marketplace?type=actions&query=maven

Unfortunately this will not help, as we have a whitelist of actions we are allowed to use.

**Comment by brunoborges** [comment]
> Unfortunately this will not help, as we have a whitelist of actions we are allowed to use.

Asking maintainers of an action that is whitelisted by your organization to include features available on non-whitelisted (by your org) actions seems a very weird way to workaround the inevitable conversation you should've having with your bosses.

**Comment by obfischer** [comment]
> Asking maintainers of an action that is whitelisted by your organization to include features available on non-whitelisted (by your org) actions seems a very weird way to workaround the inevitable conversation you should be having with your bosses.

Maybe, maybe not. I see it like this: This action provides Java and Maven. Java is configurable, Maven not. For me it would be total fine to remove the Maven part and to provide it as dedicated action. Would be even a better separation of concerns.

**Comment by garydgregory** [comment]
> > Asking maintainers of an action that is whitelisted by your organization to include features available on non-whitelisted (by your org) actions seems a very weird way to workaround the inevitable conversation you should be having with your bosses.
> 
> Maybe, maybe not. I see it like this: This action provides Java and Maven. Java is configurable, Maven not. For me it would be total fine to remove the Maven part and to provide it as dedicated action. Would be even a better separation of concerns.

Well, that makes sense indeed :-) A key part of this is that this would be an official GH action,  not a random 3rd party action.

**Comment by joschi** [comment]
> This action provides Java and Maven.

This action provides a JDK. Maven is preinstalled on the action runners. :wink:

It sounds like you would best write your own action for installing arbitrary versions of Maven, maybe forked from one of the existing actions from the market place.

**Comment by brunoborges** [comment]
While this action does not install Maven, it does have features for configuring it.

That alone is more than this action should be doing.

I wish we can separate that to a new action, along with a v3 for this one without build tool related features.

**Comment by Donnadam** [comment]
IAM so sick at a hours of the day & night these stupid texts about Builds

Donna Murdoch

**Comment by obfischer** [comment]
I think the documentation should mention, that this action relies on the Maven version installed on the runner. 

I will file an pull request with some notes.

**Comment by brunoborges** [comment]
@obfischer you might be surprised but this action configures Maven in a way that such configuration will be picked up by Maven Wrapper, which then, can be almost any version of Maven.

**Comment by joschi** [comment]
I'll just leave this here for your consideration:
```text
# mvn -q -N io.takari:maven:0.7.7:wrapper -Dmaven=3.5.4 && ./mvnw -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /path/to/.m2/wrapper/dists/apache-maven-3.5.4-bin/4lcg54ki11c6mp435njk296gm5/apache-maven-3.5.4
Java version: 11.0.13, vendor: Eclipse Adoptium, runtime: /path/to/.asdf/installs/java/temurin-11.0.13+8
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.1", arch: "x86_64", family: "mac"

# mvn -q -N io.takari:maven:0.7.7:wrapper -Dmaven=3.6.3 && ./mvnw -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /path/to/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.13, vendor: Eclipse Adoptium, runtime: /path/to/.asdf/installs/java/temurin-11.0.13+8
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.1", arch: "x86_64", family: "mac"

# mvn -q -N io.takari:maven:0.7.7:wrapper -Dmaven=3.8.4 && ./mvnw -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /path/to/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 11.0.13, vendor: Eclipse Adoptium, runtime: /path/to/.asdf/installs/java/temurin-11.0.13+8
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "11.6.1", arch: "x86_64", family: "mac"
```

**Comment by Donnadam** [comment]
Take me out of this thread I am sick of deleting  several emails a day. I
unsubscribed from GitHub 3 months ago.
***@***.***
