### ISSUE TITLE
Oracle Distribution is not supported after- release 3.8.0 

### ISSUE THREAD

**Issue by shayrapetyan11** [actions/setup-java#424]
**Description:**
Oracle distribution is not supported from 3.8.0 version.

**Task version:**
v3.8.0

**Platform:**
- Ubuntu

**Runner type:**
-  Hosted

**Repro steps:**  
    - name: Set up JDK
      uses: actions/setup-java@v3.8.0
      with:
        java-version: '17'
        distribution: 'oracle'

**Expected behavior:**
 Correct JDK version is installed

  Resolved latest version as 17
  Trying to download...
  Downloading Java [17](https://github.com/ProScanImaging/proscan-service/actions/runs/3619200145/jobs/6099962259#step:3:18) (Oracle) from https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz ...
  Extracting Java archive...
  /usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/a4825270-02bd-4394-9ade-e0c227bbc9fe -f /home/runner/work/_temp/3ce0ac66-9359-4c9b-aa68-095470353723
  Java 17 was downloaded
  Setting Java 17 as the default
  Creating toolchains.xml for JDK version 17 from oracle
  Writing to /home/runner/.m2/toolchains.xml
  
  Java configuration:
    Distribution: oracle
    Version: 17
    Path: /opt/hostedtoolcache/Java_Oracle_jdk/17/x64
  

**Actual behavior:**
error log 

Error: No supported distribution was found for input oracle

**Comment by panticmilos** [comment]
hi @shayrapetyan11, I will close this issue for now since I think it got some visibility, but we have other issues/PRs where we discuss this.

Feel free to reopen it if you think there is a need.
