### ISSUE TITLE
Maven repository repo.spring.io should not be used

### ISSUE THREAD

**Issue by theotherp** [actions/setup-java#438]
**Description:**
My builds suddenly fail because repo.spring.io returns a 401 for this artifact: https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.10.0/spring-cloud-bindings-1.10.0.jar. See example build: https://github.com/theotherp/nzbhydra2/actions/runs/3849607978/jobs/6558802340 As mentioned [here](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) the spring.io repo should not be used for releases. I'm not using a custom `settings.xml` and have this repo not configured in my pom.xml files.

While it worked before I'm *guessing* that some change in their repo now prevents the download which is why this suddenly is a problem. It looks to me like the default `settings.xml` configures this repo.

**Task version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
See above. Or have a maven build that downloads `spring-cloud-bindings:1.0.0`.

**Comment by theotherp** [comment]
This also happens locally on a fresh distro install. Seems to be baked into the `spring-boot-maven-plugin`

**Comment by theotherp** [comment]
See https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023

**Comment by e-korolevskii** [comment]
Hello @theotherp!
As I see, you were able to solve it yourself. Do you have additional questions?

Have a good day!

**Comment by theotherp** [comment]
No thank you, all is well :-)
