### ISSUE TITLE
Add Alibaba Dragonwell JDK

### ISSUE THREAD

**Issue by Accelerator1996** [actions/setup-java#443]
**Description:**
We want to add Alibaba Dragonwell JDK into setup-java so that users can use it conveniently.

**Comment by panticmilos** [comment]
hi, @Accelerator1996 thank you for submitting the report, we will take a look at it.

**Comment by IvanZosimov** [comment]
Hi, @Accelerator1996 👋 I'm closing this issue as a duplicate of the https://github.com/actions/setup-java/issues/71.. You can keep track of the issue there.

**Comment by Accelerator1996** [comment]
> Hi, @Accelerator1996 👋 I'm closing this issue as a duplicate of the #71. You can keep track of the issue there.

Thank you very much
