### ISSUE TITLE
Upgrade to Node.js 16

### ISSUE THREAD

**Issue by mirvnillith** [actions/setup-java#445]
**Description:**
Upgrade to Node.js 16 to still work when 12 is removed.

**Justification:**
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-java@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Are you willing to submit a PR?**
Sry, no

**Comment by dmitry-shibanov** [comment]
Hello @mirvnillith. We updated the Nodejs version in [v3.0.0](https://github.com/actions/setup-java/releases/tag/v3.0.0) major tag (`v3`). I think you can switch to it because it is the only one breaking change.

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the issue because the v3 tag was switched to Node.js 16.
