### ISSUE TITLE
gpg: signing failed: No secret key

### ISSUE THREAD

**Issue by nikialeksey** [actions/setup-java#447]
**Description:**
I'm trying to use setup-java action to publish my project to the maven central. When I run `maven deploy` I got the error:

```
Creating settings.xml with server-id: ossrh
Writing to /home/runner/.m2/settings.xml
Importing private gpg key

...

gpg: signing failed: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.997 s
[INFO] Finished at: 2023-01-19T14:15:04Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project jhunspell: Exit code: 2 -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```
 
**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
I use next yml config:
```yml
name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Publish
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
```

Here is my secret key names:
![secret keys names](https://user-images.githubusercontent.com/5731084/213465908-9a9392d7-7ff7-4798-896b-21952dc29dc8.png)
I've generated `OSSRH_GPG_SECRET_KEY` using 
```bash
gpg --armor --export-secret-keys D299CD6D > gpg_key.asc
```
`D299CD6D` - is my public key ID
I've also added 
```xml
<configuration>
  <gpgArguments> 
    <arg>--pinentry-mode</arg>
    <arg>loopback</arg>
  </gpgArguments>
</configuration>
```
to the my root `pom.xml` gpg plugin block.

https://github.com/nikialeksey/jhunspell - this is link to the project where I found this issue

**Expected behavior:**
gpg key imported and maven sign plugin works as expected.

**Actual behavior:**
maven sign plugin throw an error 
```
 Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project jhunspell: Exit code: 2
```

**Comment by IvanZosimov** [comment]
Hi, @nikialeksey 👋 Thanks for the issue, we'll investigate it and get back to you with updates.

**Comment by IvanZosimov** [comment]
Hi, @nikialeksey, I recommend you check your secrets one more time:
1. OSSRH_GPG_SECRET_KEY, not the OSSRH_GPG_SECRET_KEY_PASSWORD (as you wrote in the issue) should be your private key and you can generate it with `gpg --armor --export-secret-keys D299CD6D > gpg_key.asc`

If this it was just a mistake in the issue description, please, let me know to proceed with the investigation.

**Comment by nikialeksey** [comment]
@IvanZosimov Thank you! Yes, it was an error in the issue description, fixed. Anyway, I've just regenerated my key, and run the build, and logs contains the same error:
https://github.com/nikialeksey/jhunspell/actions/runs/3968843451/jobs/6802544461

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project jhunspell: Exit code: 2
```

**Comment by nikialeksey** [comment]
I don't understand why, but it is fixed when I generated new key pair and uploaded new private key to the my secrets. May be it is about key algorithms, in my old key I used rsa2048, in the new key - cv25519.

**Comment by IvanZosimov** [comment]
Hi, @nikialeksey, Thanks for your comment ❤️ !
