### ISSUE TITLE
Dynamic Java supported versions

### ISSUE THREAD

**Issue by Javabien** [actions/setup-java#452]
**Description:**
I would like to know the accurate list of versions that are supported dynamically.

**Justification:**
For now the main page only show the latest version of Java is 17, but if we use Java 19 it would still work, which means we have no official list of supported Java 19, we have try them to see if it works.

**Are you willing to submit a PR?**

**Comment by IvanZosimov** [comment]
Hi, @Javabien 👋 Thanks for the issue, could you clarify, are you talking about [this](https://github.com/actions/setup-java#supported-version-syntax) chapter in the README file ? Do you want us to update it to include 19th version ?

**Comment by IvanZosimov** [comment]
Just a gentle ping, @Javabien 📟

**Comment by IvanZosimov** [comment]
I'm closing this issue because of the lack of activity from the issue starter.
