### ISSUE TITLE
Corrupted Maven cache ?

### ISSUE THREAD

**Issue by sbernard31** [actions/setup-java#459]
Since several days, all my build faired because of : 
```
Error:  Failed to execute goal net.revelc.code:impsort-maven-plugin:1.6.2:check (default-cli) on project leshan-core: 
Execution default-cli of goal net.revelc.code:impsort-maven-plugin:1.6.2:check failed: 
A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.6.2:check: org/codehaus/plexus/util/DirectoryScanner
```

Locally I haven't any issue with this maven goal.

I'm currently using maven cache: 
```yml
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
```

And my current bet is that maybe the cache is corrupted.

My questions : 
- Is it possible ?
- how maven cache is shared ? (I mean is it share by project, by PR  or ?)
- what is the right way to re-initialize the cache ? 

(clearly this is not really a bug nor a feature request :grimacing:, sry about that)

**Comment by dmitry-shibanov** [comment]
Hello @sbernard31. Thank you for your report. You can try to remove the specific cache with this menu on Actions tab. Besides, I think the issue can be related to the maven version. You can try to use community actions to change Maven version or Maven Wrapper. 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/28229110/222958518-a2d11c32-1e17-4dc4-b295-38f2339549dd.png">

**Comment by sbernard31** [comment]
@dmitry-shibanov, I tested to remove cache and still face same issue. 

I will investigate around maven version. (I let you know if I find something)
