### ISSUE TITLE
Unknown distribution 'semeru'

### ISSUE THREAD

**Issue by bmarwell** [actions/setup-java#471]
**Description:**

'semeru' is not recognized although this was merged:
https://github.com/OpenLiberty/ci.maven/actions/runs/4505417141/jobs/7931110701?pr=1654

**Task version:**

v3

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

Run a job with `distribution: semeru`.

**Expected behavior:**

IBM Semeru being installed.

**Actual behavior:**

`ERROR: Unknown distribution 'semeru'`

**Comment by dmitry-shibanov** [comment]
Hello @bmarwell. Thank you for your report. For now we have not released a new version of the action. You can try to specify `actions/setup-java@main` for now.

**Comment by dmitry-shibanov** [comment]
Hello @bmarwell. We released a new version ([3.11.0](https://github.com/actions/setup-java/releases/tag/v3.11.0)) of action and updated the major tag. Could you please confirm that everything works as expected ?

**Comment by bmarwell** [comment]
Yes, works flawlessly! Tested on a branch from OpenLiberty/ci.maven.

Thanks!

**Comment by bmarwell** [comment]
Yes, works flawlessly! Tested on a branch from OpenLiberty/ci.maven.

Thanks!
