### ISSUE TITLE
Add a new configuration to set a custom cache key.

### ISSUE THREAD

**Issue by ouaibsky** [actions/setup-java#490]
**Description:**
Add a new configuration to set a custom cache key.

**Justification:**
* I have a workflow that touch the pom leading to invalidate the cache after each run.
* Some of my other projects use native compilation, meaning compiling in Windows, Mac, and Linux and I would like to share maven local cache.
* optionally i don't understand why the cache key is per platform / packager / pom hash. Java is multiform, we have one maven central whatever the platform you are using, cache should reflect that.
  * If you thing your cache is corrupted (really rare), just trash it.

**Are you willing to submit a PR?**
why not, I'm a coder but no strong skills with ts.

Chris.

**Comment by IvanZosimov** [comment]
Hi, @ouaibsky 👋 Thanks for the issue! Cache strategy in our action is chosen according to the recommendations from the [cache](https://github.com/actions/cache/blob/main/examples.md#java---maven) action. If you need other behavior, you can turn off the caching in our action and instead rely on [actions/cache](https://github.com/actions/cache/tree/main) which you can configure by yourself. I'm closing this issue now, If you have any questions feel free to ask me.
