### ISSUE TITLE
Maven deploy doesn't work

### ISSUE THREAD

**Issue by rhyslewisakl** [actions/setup-java#497]
**Description:**
If I follow the the instructions here: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven I get a permissions error when trying to upload a maven package to Github.

**Task version:**
v3

**Platform:**
- [*] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [*] Hosted
- [ ] Self-hosted

**Repro steps:**  

I have created a hello world public repo here: https://github.com/rhyslewisakl/testsetupjavaaction that demonstrates the problem.

I would like this code in the action:

```
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
```

to upload a package.  Instead it says:

```
/home/runner/.m2/repository/info/rhyslewis/testsetupjavaaction/0.0.1/testsetupjavaaction-0.0.1.jar
[INFO] Installing /home/runner/work/testsetupjavaaction/testsetupjavaaction/pom.xml to /home/runner/.m2/repository/info/rhyslewis/testsetupjavaaction/0.0.1/testsetupjavaaction-0.0.1.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ testsetupjavaaction ---
Uploading to github: https://maven.pkg.github.com/rhyslewisakl/testsetupjavaaction/info/rhyslewis/testsetupjavaaction/0.0.1/testsetupjavaaction-0.0.1.jar
Progress (1): 2.7 kB
                    
Uploading to github: https://maven.pkg.github.com/rhyslewisakl/testsetupjavaaction/info/rhyslewis/testsetupjavaaction/0.0.1/testsetupjavaaction-0.0.1.pom
Progress (1): 2.8 kB
                    
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.881 s
[INFO] Finished at: 2023-06-04T21:02:20Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project testsetupjavaaction: Failed to deploy artifacts: Could not transfer artifact info.rhyslewis:testsetupjavaaction:jar:0.0.1 from/to github (https://maven.pkg.github.com/rhyslewisakl/testsetupjavaaction): authorization failed for https://maven.pkg.github.com/rhyslewisakl/testsetupjavaaction/info/rhyslewis/testsetupjavaaction/0.0.1/testsetupjavaaction-0.0.1.jar, status: 403 Forbidden -> [Help 1]
Error:  
```

**Expected behavior:**
I expect the package to be uploaded to the Github repo

**Actual behavior:**
There is an error saying that the runner is not authorised to upload the package.

**Comment by TomVanWemmel** [comment]
@rhyslewisakl 
Did you try adding package permissions?
```
permissions:
      packages: write
```

**Comment by rhyslewisakl** [comment]
Thanks, that seems to have fixed it.

 I will add a pull request to the documentation to add that.
 
 The curious thing is that I have several other private repos that started failing with this problem a few months ago (it's taken a while to report the problem).  I've made this change to two of those repos and they are back to building and deploying OK again.  Did something change in the back end recently?  It would be good to update the documentation when something like that changes.

**Comment by esdrasdemorais** [comment]
I changed my artifact id in pom.xml file from Upper Case to Lower Case and solved my issue.
