### ISSUE TITLE
Support Scala on MacOS

### ISSUE THREAD

**Issue by cjyar** [actions/setup-java#50]
This action appears to install sbt on `ubuntu-18.04`, but not on `macos-10.15`.

**Comment by konradpabjan** [comment]
I would file an issue in actions [virtual-environments](https://github.com/actions/virtual-environments) repository. Scala gets installed differently than Java.

For ubuntu, it looks like `scala` gets installed from [here](https://github.com/actions/virtual-environments/blob/51d02f26f42e53bb963bb6bc9754501b28a3d2ba/images/linux/scripts/installers/sbt.sh)
