### ISSUE TITLE
Error due to download size of cache

### ISSUE THREAD

**Issue by tassilo-posegga** [actions/setup-java#506]
**Description:**
Trying to use the setup action for the first time in my unit test workflow for Android. I am not getting past setting up java - as it fails due to en error. We have quite a big gradle cache (not configured, default to GHA).

```
jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
```
```

Run actions/setup-java@v2
Resolved Java 17.0.7+7 from tool-cache
Setting Java 17.0.7+7 as the default

Java configuration:
  Distribution: temurin
  Version: 17.0.7+7
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.7-7/x64

Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Received 0 of 8560807682 (0.0%), 0.0 MBs/sec
Received 58720256 of 8560807682 (0.7%), 28.0 MBs/sec
Received 167772160 of 8560807682 (2.0%), [53](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:54).3 MBs/sec
Received 272629760 of 8560807682 (3.2%), 65.0 MBs/sec
Received 373293056 of 8560807682 (4.4%), 71.2 MBs/sec
Received 473956352 of 8560807682 (5.5%), 75.3 MBs/sec
Received 578813952 of 8560807682 (6.8%), 78.8 MBs/sec
Received 679477248 of 8560807682 (7.9%), 81.0 MBs/sec
Received 771751936 of 8560807682 (9.0%), 81.7 MBs/sec
Received 864026624 of 8560807682 (10.1%), 82.3 MBs/sec
Received 956301312 of 8560807682 (11.2%), 82.8 MBs/sec
Received 1044381696 of 8560807682 (12.2%), 82.9 MBs/sec
Received 1119879168 of 8560807682 (13.1%), 82.0 MBs/sec
Received 1199570944 of 8560807682 (14.0%), 81.6 MBs/sec
Received 1287651328 of 8560807682 (15.0%), 81.8 MBs/sec
Received 1367343104 of 8560807682 (16.0%), 81.4 MBs/sec
Received 1430257664 of 8560807682 (16.7%), 80.1 MBs/sec
Received 1501560832 of 8560807682 (17.5%), 79.4 MBs/sec
Received 1572864000 of 8560807682 (18.4%), 78.8 MBs/sec
Received 1639972864 of 8560807682 (19.2%), 78.1 MBs/sec
Received 1723858944 of 8560807682 (20.1%), 78.1 MBs/sec
Received 1790967808 of 8560807682 (20.9%), 77.5 MBs/sec
Received 1853882368 of 8560807682 (21.7%), 76.7 MBs/sec
Received 1920991232 of 8560807682 (22.4%), 76.2 MBs/sec
Received 1983905792 of 8560807682 (23.2%), 75.6 MBs/sec
Received 2055208960 of 8560807682 (24.0%), 75.3 MBs/sec
Received 2126512128 of 8560807682 (24.8%), 75.0 MBs/sec
Received 2193620992 of 8560807682 (25.6%), 74.6 MBs/sec
Received 2256535552 of 8560807682 (26.4%), 74.1 MBs/sec
Received 2327838720 of 8560807682 (27.2%), 73.9 MBs/sec
Received 2399141888 of 8560807682 (28.0%), 73.7 MBs/sec
Received 2466250752 of 8560807682 (28.8%), 73.4 MBs/sec
Received 2529165312 of 8560807682 (29.5%), 73.0 MBs/sec
Received 2600468480 of 8560807682 (30.4%), 72.8 MBs/sec
Received 2675965952 of 8560807682 (31.3%), 72.8 MBs/sec
Received 2751463424 of 8560807682 (32.1%), 72.8 MBs/sec
Received 2818572288 of 8560807682 (32.9%), 72.6 MBs/sec
Received 288987[54](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:55)56 of 8560807682 (33.8%), 72.4 MBs/sec
Received 2952790016 of 8560807682 (34.5%), 72.1 MBs/sec
Received 3024093184 of 8560807682 (35.3%), 72.0 MBs/sec
Received 3099590656 of 8560807682 (36.2%), 72.0 MBs/sec
Received 3166699520 of 8560807682 (37.0%), 71.8 MBs/sec
Received 3246391296 of 8560807682 (37.9%), 71.9 MBs/sec
Received 3321888768 of 8560807682 (38.8%), 71.9 MBs/sec
Received 3397386240 of 8560807682 (39.7%), 71.9 MBs/sec
Received 3477078016 of 8560807682 (40.6%), 72.0 MBs/sec
Received 3[55](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:56)6769792 of 8[56](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:57)0807682 (41.5%), 72.1 MBs/sec
Received 3632267264 of 8560807682 (42.4%), 72.1 MBs/sec
Received 3711959040 of 8560807682 (43.4%), 72.2 MBs/sec
Received 3795845120 of 8560807682 (44.3%), 72.3 MBs/sec
Received 3871342592 of 8560807682 (45.2%), 72.3 MBs/sec
Received 394264[57](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:58)[60](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:61) of 8560807682 (46.1%), 72.2 MBs/sec
Received 4018143232 of 8560807682 (46.9%), 72.2 MBs/sec
Received 4093640704 of 8560807682 (47.8%), 72.2 MBs/sec
Received 4160749568 of 8560807682 (48.6%), 72.1 MBs/sec
Received 423[62](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:63)47040 of 8560807682 (49.5%), 72.1 MBs/sec
Received 4286578688 of 8560807682 (50.1%), 71.6 MBs/sec
Received 4294967296 of 8560807682 (50.2%), 71.6 MBs/sec
Error: The value of "length" is out of range. It must be >= 0 && <= 2147483[64](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:65)7. Received 42949[67](https://github.com/XXX/android-core/actions/runs/5448084051/jobs/9910856955#step:3:68)296
```

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
No crash

**Actual behavior:**
Crash due to things being downloaded through the java setup task. My assumption is that it is some gradle cache?

**Comment by IvanZosimov** [comment]
Hi, @tassilo-posegga 👋 Thanks for the issue, we will take a look and get back to you with updates.

**Comment by vigneswaranm89** [comment]
we are also getting similar kind of issue 

`      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: '13'
          distribution: 'adopt'
          cache: maven
`


`Trying to resolve the latest version from remote
Resolved latest version as 13.0.2+8.1
Trying to download...
Downloading Java 13.0.2+8.1 (Adopt-Hotspot) from https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_linux_hotspot_13.0.2_8.tar.gz ...
Extracting Java archive...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/85f8b281-e63d-4d9a-bcb0-878c147418f8 -f /home/runner/work/_temp/37e5a8bd-7555-48d9-9cda-43dc5e2c54ae
Java 13.0.2+8.1 was downloaded
Setting Java 13.0.2+8.1 as the default

Java configuration:
  Distribution: adopt
  Version: 13.0.2+8.1
  Path: /opt/hostedtoolcache/Java_Adopt_jdk/13.0.2-8.1/x64

Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Received 46137344 of 3959032006 (1.2%), 44.0 MBs/sec
Received 226492416 of 3959032006 (5.7%), 107.9 MBs/sec
Received 436207616 of 3959032006 (11.0%), 138.4 MBs/sec
Received 637534208 of 3959032006 (16.1%), 
Received 826277888 of 3959032006 (20.9%), 157.4 MBs/sec
Received 1006632960 of 3959032006 (25.4%), 159.8 MBs/sec
Received 1195376640 of 3959032006 (30.2%), 
Received 1363148800 of 3959032006 (34.4%), 162.2 MBs/sec
Received 1543503872 of 3959032006 (39.0%), 163.1 MBs/sec
Received [17164.4 MBs/sec
Received 1929379840 of 3959032006 (48.7%), 166.7 MBs/sec
Received 2126512128 of 3959032006 (53.7%), 168.4 MBs/sec
Received 2298478592 of 3959032006 (58.1%), 168.1 MBs/sec
Received 2474639360 of 3959032006 (62.5%), 168.1 MBs/sec
Received 2860515328 of 3959032006 (72.3%), 170.0 MBs/sec
Received 3250585600 of 3959032006 (82.1%), 171.7 MBs/sec
Received 3430940672 of 3959032006 (86.7%), 171.6 MBs/sec
Received 3628072960 of 3959032006 (91.6%), 172.4 MBs/sec
Received 3829399552 of 3959032006 (96.7%), 173.2 MBs/sec
Received 3959032006 of 3959032006 (100.0%), 173.7 MBs/sec
Error: The value of "length" is out of range. It must be >= 0 && <= [21]

**Comment by IvanZosimov** [comment]
Hi, @vigneswaranm89 👋 Could you, please, provide us with the workflow run?

**Comment by IvanZosimov** [comment]
@tassilo-posegga and @vigneswaranm89 just a gentle ping 📟

**Comment by IvanZosimov** [comment]
@tassilo-posegga and @vigneswaranm89 just a gentle ping 📟

**Comment by IvanZosimov** [comment]
I'm closing this issue as inactive.
