### ISSUE TITLE
Request times out on "trying to resolve the latest version from remote"

### ISSUE THREAD

**Issue by rome-user** [actions/setup-java#508]
**Description:**
I am using a self-hosted Gitea/Forgejo Actions, and for some reason, setup-java@v3 just hangs and never works. The IP address is from OVH. I don't see it listed on Spamhaus or other blacklists. So I don't know what's going on.

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
N/A

**Expected behavior:**
I can proceed with Java installed.

**Actual behavior:**
After minutes of seeing "trying to resolve the latest version", I see this.
```
::group::Installed distributions
Trying to resolve the latest version from remote
::error::Request timeout: /v3/assets/version/%255B1.0,100.0%255D?project=jdk&vendor=adoptium&heap_size=normal&sort_method=DEFAULT&sort_order=DESC&os=linux&architecture=x64&image_type=jdk&release_type=ga&jvm_impl=hotspot&page_size=20&page=0
```

**Comment by dusan-trickovic** [comment]
Hello, @rome-user ! Thank you for creating the issue! We will investigate it further and see what can be done and where seems to be the problem :)

**Comment by IvanZosimov** [comment]
Hi, @rome-user 👋 Could you provide us with your workflow file (with exact workflow which is failed) and also could you check whether you can make a get request to this URL using any tool for making requests (e.g. curl): https://api.adoptium.net/v3/assets/version/%5B1.0,100.0%5D?project=jdk&vendor=adoptium&heap_size=normal&sort_method=DEFAULT&sort_order=DESC&os=linux&architecture=x64&image_type=jdk&release_type=ga&jvm_impl=hotspot&page_size=20&page=0

**Comment by IvanZosimov** [comment]
Thanks for the clarification, @rome-user! I see that for running `curl` you used `alpine/curl` but what image did you use for running the workflow (with setup-java) using act-runner?

**Comment by IvanZosimov** [comment]
Yes, I got your point, but I'd like to check whether it's possible to get access to the link from the runner which is used to run `setup-java`. Maybe you can try to install curl to the https://github.com/vegardit/docker-gitea-act-runner and try to use it from there?

**Comment by IvanZosimov** [comment]
Hi, @rome-user 👋 It seems that you have some SSL problems and these problems are related to your self-hosted runner settings. Unfortunately, I can only recommend you to create an issue here https://github.com/vegardit/docker-gitea-act-runner, because currently it seems like it's not a responsibility of the action itself.
