### ISSUE TITLE
Upgrade node version from 12 to 16

### ISSUE THREAD

**Issue by ChrisBafaro** [actions/setup-java#517]
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-java@v2.
For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by dusan-trickovic** [comment]
Hello @ChrisBafaro ! Thank you for creating the issue, we'll take a closer look at it :)

**Comment by IvanZosimov** [comment]
Hi, @ChrisBafaro 👋 The current version of the action is v3 and and this version is updated to use node16. So in this case you may want to switch to the v3 version and this will solve the issue.

I'm going to close this issue, If you have any additional questions feel free to ping me.

**Comment by ChrisBafaro** [comment]
Hi @IvanZosimov, thank you.
I didn't see that there was a new version available.
Thank you
