### ISSUE TITLE
1.x versions does not work with the tools cache

### ISSUE THREAD

**Issue by plamentotev** [actions/setup-java#54]
When Java package is added to the cache it is added using the package version. For example 8.0.181. When a Java package is looked up in the tool cache the version supplied by the user is used. That could be either 8 or 1.8. Both should match 8.0.181, but as you can expect `tc.find` won't match 1.8.

**Comment by dmitry-shibanov** [comment]
Hello @plamentotev. Recently we released `setup-java@v2` and the new version does not support legacy syntax like `1.x`. Please consider using new syntax. You can see migration guide from `v1` to `v2` [here](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md). If you have any concerns feel free to reopen the issue.
