### ISSUE TITLE
Update to node20

### ISSUE THREAD

**Issue by benwells** [actions/setup-java#544]
**Description:**
Node 16 has reached end of life on September 11, 2023.

https://github.com/actions/runner now supports node 20 as of [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) and we encourage teams to update their actions to run on node 20 runtime by default. 

[Changelog here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by IvanZosimov** [comment]
Hi, @benwells 👋 Thanks for the notification!

**Comment by LVMVRQUXL** [comment]
+1 for this issue.

Here's an example of workflow using [actions/setup-java@v3.11.0](https://github.com/actions/setup-java/releases/tag/v3.11.0) that shows the corresponding deprecation notice: [Kotools Types Integration #370](https://github.com/kotools/types/actions/runs/6632708905).
