### ISSUE TITLE
Add support for microsoft openjdk 21.0.0

### ISSUE THREAD

**Issue by ralfstuckert** [actions/setup-java#545]
**Description:**
Extend the microsoft-openjdk-versions.json with version 21.0.0

**Justification:**
Stable version 21.0.0 is available, and the microsoft-openjdk-versions.json has to be maintained in order to use that version.

**Are you willing to submit a PR?**
yep

**Comment by marko-zivic-93** [comment]
Hello @ralfstuckert 
Thank you for the feature request. We will take a look and come back to you with further steps. 🙂

**Comment by IvanZosimov** [comment]
Hi, @ralfstuckert 👋 The [new major version of the action](https://github.com/actions/setup-java/releases/tag/v4.0.0) is released and it contains the requested changes.
I'm closing this issue, if you have any additional questions feel free to reach out.
