### ISSUE TITLE
README: update the `java-version` list

### ISSUE THREAD

**Issue by exhviewer** [actions/setup-java#557]
**Description:**
Java LTS version 21 has been available for some time now, but the repository is still not updated.

**Justification:**
Version 21 deserves to be in the list as an LTS version.

**Are you willing to submit a PR?**
No, sorry.

**Comment by SethTisue** [comment]
Doesn't it already work? I'm using it at e.g. https://github.com/SethTisue/Project-Euler/blob/main/.github/workflows/ci.yml and in a number of other repos I do work in.

**Comment by exhviewer** [comment]
> Doesn't it already work? I'm using it at e.g. https://github.com/SethTisue/Project-Euler/blob/main/.github/workflows/ci.yml and in a number of other repos I do work in.

Yes, it can be used. It just hasn't been [tested](https://github.com/actions/setup-java/blob/main/__tests__/distributors/temurin-installer.test.ts).

It's also not in the [README](https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax), but you do have access to it.

**Comment by IvanZosimov** [comment]
Hi, @exhviewer  👋 As @SethTisue mentioned, Temurin 21 can be set up in the current version of setup-java. Nevertheless, thank you for the issue, we will update documentation.

**Comment by Khant-NyarxG-Next** [comment]
i want to make with kotlin 
compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    
  i try so many way but don't worked 
  
  
<img width="1440" alt="image" src="https://github.com/actions/setup-java/assets/138663777/97252409-376e-48b1-9820-3b9392953579">

**Comment by IvanZosimov** [comment]
Hi, @Khant-NyarxG-Next 👋 Could you please create a new issue with the full context? Currently, it's not quite clear what problem you're trying to report.

**Comment by Khant-NyarxG-Next** [comment]
> Hi, @Khant-NyarxG-Next 👋 Could you please create a new issue with the full context? Currently, it's not quite clear what problem you're trying to report.

thanks for response but i have been solve the problem .i create ci for my koylin app and in yout dons i don't find the correct version of java and i found the solution from somewhere no it worked with  
        distribution: temurin
        java-version: 21

**Comment by AleksandarTokarev** [comment]
It would be great if the README is updated with Java 21 - so people are not mislead that it does not work with Java 21.
