### ISSUE TITLE
The resulting JAVA_HOME_..._architecture variable name is inconsistent: ARM64 or AARCH64

### ISSUE THREAD

**Issue by vlsi** [actions/setup-java#561]
**Description:**

The environment variable name is inconsistent: sometimes it is `JAVA_HOME_17_AARCH64` and sometimes it is `JAVA_HOME_17_ARM64`.

https://github.com/actions/setup-java/blob/9eda6b51cc4f6ee99be3dd5537b85e389e47bda9/src/distributions/base-installer.ts#L172

**Task version:**

'actions/setup-java@v3' (SHA:0ab4596768b603586c0de567f2430c30f5b0d2b0)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**

The variable name should be consistent.
Preferably, the variable name should use the same values as the action's `architecture` input parameter: https://github.com/actions/setup-java/blob/9eda6b51cc4f6ee99be3dd5537b85e389e47bda9/README.md#L36

**Actual behavior:**

If user omits `architecture`, then `setup-java` generates `JAVA_HOME_17_ARM64` environment variable.
If user passes `architecture: aarch64`, then `setup-java` generates `JAVA_HOME_17_AARCH64` variable.

**Comment by mahabaleshwars** [comment]
Hello @vlsi,
The architecture variable defaults to the runner image's architecture when not provided, and it uses the architecture variable provided by the user accordingly. We believe this is the expected behavior. Additionally, there might be confusion if a different value is printed when the user specifies the architecture variable. Could you please let us know if this is causing any issues while running the workflows?

**Comment by mahabaleshwars** [comment]
Hello @vlsi, can you confirm if the above feedback resolves the issue? If not, could you share the issues you are facing?

**Comment by mahabaleshwars** [comment]
Hello @vlsi, just a friendly reminder to confirm if the above feedback resolves the issue. If not, could you please share any issues you are still facing?

**Comment by mahabaleshwars** [comment]
Hello @vlsi, I am closing this issue now. Please feel free to reach out to us if you encounter any other issues.
