### ISSUE TITLE
Admob

### ISSUE THREAD

**Issue by a2425rdl** [actions/setup-java#578]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [x] Ubun
[Website-Privacy-Policy-English.pdf](https://github.com/actions/setup-java/files/13786396/Website-Privacy-Policy-English.pdf)
tu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by IvanZosimov** [comment]
Closed as a spam.
