### ISSUE TITLE
Get Java version from .tool-versions file

### ISSUE THREAD

**Issue by paulschreiber** [actions/setup-java#579]
**Description:**
Please add support for getting the Java version from the `.tool-versions` file.

**Justification:**
This is supported by `actions/setup-node`, which we also use. Having a separate `.java-version` file ([added in 3.9.0](https://github.com/actions/setup-java/releases/tag/v3.9.0)) is less efficient.

**Comment by aparnajyothi-y** [comment]
Hello @paulschreiber, Thanks for the feature request, we will take a look and get back to you with our decision.

**Comment by mahabaleshwars** [comment]
Hi @paulschreiber,
We have added the functionality to extract the Java version from a .tool-versions file in actions/setup-java@v4.2.2. Hence we are proceeding to close this issue. 
Please feel free to reach us in case of any further concerns/clarifications needed.

**Comment by paulschreiber** [comment]
Thanks. Can you update the README with an example? i.e. do I use
```java-version-file: '.tool-versions'```

as with `actions/setup-node`?
