### ISSUE TITLE
Permission denied in post job cleanup on Windows

### ISSUE THREAD

**Issue by LVMVRQUXL** [actions/setup-java#583]
**Description:**
I'm getting a `permission denied` error in the post job cleanup step on Windows.

Here's a screenshot of the corresponding run in [kotools/types/integration#7411214442](https://github.com/kotools/types/actions/runs/7411214442/job/20165270927#step:9:5) workflow:

![Screenshot](https://github.com/actions/setup-java/assets/43500570/fc499912-cbb4-4b46-b169-56b42016da8e)

**Task version:**
3.11.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Comment by mahabaleshwars** [comment]
Hello  @LVMVRQUXL, to resolve this issue, it's recommended to halt Gradle post-testing. Add the subsequent code into the workflow:
```
- name: Stop Gradle
  run: ./gradlew --stop
```

This should be inserted into your 'windows-test' job within the workflow. The reason to add this step is to ensure that the Gradle daemon isn't holding onto any file locks when the post job cleanup step runs. If the Gradle daemon is holding onto a file lock, it can cause the tar command in the post job cleanup step to fail, as you've seen. This action will enable successful cache storage. A screenshot of the adjusted workflow has been attached for your reference. Please confirm if the problem has been addressed.

**Comment by LVMVRQUXL** [comment]
Hello @mahabaleshwars. Thank you for your suggestion, but I stoped using Windows for testing projects in GitHub Actions. It takes too much time comparing to Ubuntu or macOS runners.

**Comment by mahabaleshwars** [comment]
Hi @LVMVRQUXL, the solution for the mentioned issue is provided above. Kindly verify if it resolves your problem. I'll be closing this ticket now, but don't hesitate to contact if you experience any further issues related to this ticket or any other topic.
