### ISSUE TITLE
JDK support distribution JBR (jetbrains runtime version)

### ISSUE THREAD

**Issue by Leslie-DD** [actions/setup-java#585]
Some libraries like [jewel](https://github.com/JetBrains/jewel) require the JetBrains Runtime to work correctly, but setup-java not supported yet.
Will you support JBR, and When?

**Comment by aparnajyothi-y** [comment]
Hello @Leslie-DD
Thank you for reporting this issue, We will investigate it and come back to you as soon as we have some information.

**Comment by Goooler** [comment]
Duplicate of #399.
