### ISSUE TITLE
Separate Java setup from Maven/Gradle setup

### ISSUE THREAD

**Issue by alexey-anufriev** [actions/setup-java#60]
Currently, this action provides not just Java setup but Maven/Gradle as well. And this is not very convenient due to some reasons, for example, I may want to reconfigure Maven settings between steps, but for this, I need to call the whole `setup-java` action.

**Comment by giltene** [comment]
I agree that separate setup-maven and setup-gradle action probably makes sense given the additional build-system specific items that keep coming up, including items around build system versions, credentials, etc. I expect that options for setting up or controlling gradle and maven wrappers may also come up to address needs for build system version selection in additional ways.

setup-java and setup-maven / setup-gradie should probably be two separate steps. Each should be used if control over the item they set up is needed. Some default implementation (of unspecified version or configuration) of java, maven, and gradle may already exist on the OS that allows you to skip the setup step if you don’t care about version selection or setup consistency.

**Comment by dmitry-shibanov** [comment]
Hello everyone. I'm closing this issue, because we don't have plans to add support for maven or gradle to setup-java, as it was discussed in https://github.com/actions/setup-java/issues/40.
