### ISSUE TITLE
Invalid version file after updating to 4.2.0

### ISSUE THREAD

**Issue by eygraber** [actions/setup-java#609]
**Description:**
After updating to 4.2.0 from 4.1.0 I get an error `Invalid version file`

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
https://github.com/eygraber/cmp-library-template/pull/46

**Expected behavior:**
Not to have an error

**Actual behavior:**
There is an error

**Comment by gobetti** [comment]
the issue is that @eygraber 's example project uses a file called `.ci-java-version`, and setup-java@v4.2.0 no longer accepts that, as stated in the updated readme:
> Supported files are .java-version and .tool-versions.

respective code change: https://github.com/actions/setup-java/pull/606/files#diff-8164d45a0a98040cbf5161c5b6e696920163460bea5f24100a7a01720c4a9a91R125267-R125276

I think for that change not to be a breaking change and require a bump to v5, we could keep the `java-version-file` parameter doing what it did before, and specifically work like a `.java-version` file should; that name is also more indicative of a ".java-version file" and one might not expect to use "java-version-file" to point to a "tool versions file"

**Comment by jamessmckay** [comment]
I use the .java-version file and I get the same error.

**Comment by gobetti** [comment]
@jamessmckay yeah 4.2.0 is only working for me if my file is called `.java-version` **and** I specify `java-version-file: .java-version`

**Comment by eddsteel** [comment]
Also getting this error with `./.java-version`. The workaround to use `.java-version` isn't really going to work because we use a shared action with inputs to call this one with `java-version-file: ${{ inputs.working-directory }}/.java-version`.

**Comment by HarithaVattikuti** [comment]
Hello @eygraber 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by buckett** [comment]
> I think for that change not to be a breaking change and require a bump to v5, we could keep the `java-version-file` parameter doing what it did before, and specifically work like a `.java-version` file should; that name is also more indicative of a ".java-version file" and one might not expect to use "java-version-file" to point to a "tool versions file"

If the idea is that it only supports files in the root then that seems like a breaking change and something that should be a major version bump.

**Comment by gobetti** [comment]
@parsable-danielmillen to clarify to all, I haven't contributed to this repo, I was affected by the bug just like y'all but seeing this fresh issue made me want to contribute in finding what went wrong and possible workarounds we have, so perhaps someone more familiar with the project can use that to make a more informed decision. It's clearly a breaking change that it no longer accepts something it did. But as for the original expectation, my interpretation is that they tried to allow something extra (.tool-versions), and if you mean that'd be a breaking change too, you might want to detail given the acceptance of that change may indicate not everybody sees it. Thanks!

**Comment by eygraber** [comment]
Looks like 4.2.1 fixes the issue. Will that behavior be reintroduced in v5?

**Comment by HarithaVattikuti** [comment]
Hello

Please update to 4.2.1 that accepts java version file from any path.

Feel free to reach out to us in case of any issues.

**Comment by eygraber** [comment]
Will a future version change the behavior again to only accept `.java-version`?

**Comment by HarithaVattikuti** [comment]
Hello @eygraber 

We aren't planning any revisions in this particular field for the time being. However, if such changes are introduced in the future, they will be marked as breaking changes to ensure users are aware of the potential impacts on their workflows.

Feel free to reach out to us in case of any issues.
