### ISSUE TITLE
setup-java should search in /usr/lib/jvm as well as the tool cache

### ISSUE THREAD

**Issue by rbellamy** [actions/setup-java#62]
Given that the JDKs are not installed into the hosted toolcache, the current code searching for a JDK on a GitHub hosted runner will always be a "cache miss" the first time:

https://github.com/actions/setup-java/blob/5c87b70ffefc9ca2e77153b3528c6b7bc85a84a9/src/installer.ts#L35

At the [recommendation of one of the virtual-environments maintainers](https://github.com/actions/virtual-environments/issues/852#issuecomment-626744689), I'm raising the issue here.

**Comment by giltene** [comment]
Adding a check to see if the desired version is pre-installed could make sense,a nd may reduce traffic for many common cases (latest 8, 11, 13) for several weeks at a time. But it's important to keep in mind that java packages get updated quite frequently,  and potentially more frequently than the OS images do, and that in the days or weeks immediately following a Java quarterly update, the OS-image-pre-installed java update versions is unlikely to match what e.g. "11", "8.0.x", "13", or "14" mean in semver terms: E.g. 7.0.262, 8.0.252, 11.0.7, 13.0.3, and 14.0.1 all came out on April 14, 2020, and they will all rev again on July 14 at the latest...

We could try to separate the specific version determination from the download of the determined bits. E.g. once the desired version has been determined (by scanning the CDN for semver-matching things and choosing one), we could see if the exact same package we want is already in /usr/ib/jvm, and skip the download if it is... This would certainly help reduce download bandwidth if the OS images get updated with versions from the same CDN in a timely manner (but will also likely leave traffic spikes in the days that follow each quarterly update, until the OS image catches up). It also has the downside of not address older versions (many tests like to nail down a specific update version top test against) and rapidly changing versions (e.g. the EA builds that rev as often as once a week).

An alternative (and more time-robust approach IMO) is to look to incorporate [actions/cache](https://github.com/actions/cache) in some way. This would create much more consistent caching (which would work even in the days following a quarterly update, and even for rapidly changing packages like the current 15-ea packages), and would likely reduce the download traffic loads during peak times (right after updates) better than an attempt to sync up the contents of the OS images would. It would be great if [action/cache](https://github.com/actions/cache) was directly leverageable from other actions in some way. But until it is, perhaps we can do a subtree trick like e.g. https://github.com/lukka/run-vcpkg does?

**Comment by dmitry-shibanov** [comment]
Hello everyone. We moved our precached java versions to `/opt/hostedtoolcache/Java_Adopt_jdk` directory on hosted runners. Recently we released `setup-java@v2` and new task version will be able to consume pre-installed java version. You can see migration guide from `v1` to `v2` [here](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md). If you have any concerns feel free to reopen the issue.
