### ISSUE TITLE
`actions/setup-java` is flaky

### ISSUE THREAD

**Issue by harupy** [actions/setup-java#621]
**Description:**

Thanks for maintaining this action. The `actions/setup-java` action has been flaky in our repo (https://github.com/mlflow/mlflow). Here's a failed workflow run:

https://github.com/mlflow/mlflow/actions/runs/8639947543/job/23687131186?pr=11673

```
Prepare all required actions
Getting action download info
Download action repository 'actions/setup-java@v4' (SHA:99b8673ff64fbf99d8d3[2](https://github.com/mlflow/mlflow/actions/runs/8639947549/job/23687111133?pr=11673#step:6:2)5f52d9a5bdedb8483e9)
Run ./.github/actions/setup-java
  with:
    java-version: 11
    distribution: adopt
  env:
    ...
  with:
    java-version: 11
    distribution: adopt
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
  env:
    ...
Installed distributions
  Trying to resolve the latest version from remote
```

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
...
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: adopt
```

**Expected behavior:**

No flakiness

**Actual behavior:**

Flaky

**Comment by HarithaVattikuti** [comment]
Hello @harupy 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by harupy** [comment]
Closing this. `actions/setup-java` is no longer flaky in our repo.
