### ISSUE TITLE
java.lang.IllegalAccessError: superclass access check failed with `setup-java@v4`

### ISSUE THREAD

**Issue by alghe-global** [actions/setup-java#626]
**Description:**

**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted (GitHub Actions)
- [ ] Self-hosted

**Repro steps:**  
Run gradle build with `setup-java@v4`

**Expected behavior:**
Gradle build to succeed (succeeds with `setup-java@v3`)

**Actual behavior:**
Error is thrown:

```
e: java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x7c548429) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x7c548429
```

seems it relates to https://youtrack.jetbrains.com/issue/KT-60507/Kapt-IllegalAccessError-superclass-access-check-failed-using-java-21-toolchain

**Comment by HarithaVattikuti** [comment]
Hello @alghe-global 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by mahabaleshwars** [comment]
Hello @alghe-global, Could you provide the steps to reproduce the issue or share a public repository that replicates it?

**Comment by mahabaleshwars** [comment]
Hello @alghe-global, just a friendly reminder to provide the steps to reproduce the issue or share a public repository that replicates it. Thank you!

**Comment by mahabaleshwars** [comment]
Hello @alghe-global,
We are closing this issue for now due to inactivity. Please feel free to reach out if the issue persists, and we can reopen it.
