### ISSUE TITLE
Azul distribution support

### ISSUE THREAD

**Issue by jlerbsc** [actions/setup-java#628]
Hi, Can you confirm that the azul distribution has removed versions 9, 10, 12 and 14 from their official API version?

![image](https://github.com/actions/setup-java/assets/5850581/03ee4ebc-b845-4da6-a0c2-b03198b158f4)

**Comment by aparnajyothi-y** [comment]
Hello @jlerbsc, Thank you for creating this issue and we will get back to you once we have some feedback.

**Comment by mahabaleshwars** [comment]
Hi @jlerbsc, currently, the Azul distribution supports versions 8, 11, 17, 21, and 22 only. All other versions have been removed from their official website. I've included a screenshot for your reference.

<img width="2024" alt="Screenshot 2024-05-07 at 15 08 42" src="https://github.com/actions/setup-java/assets/147705296/95d192df-2676-4f06-b208-83a70cd9185d">

**Comment by jlerbsc** [comment]
Thank you for your reply. We're going to migrate the Javaparser project to another distribution.
