### ISSUE TITLE
What version of gradle does this use?

### ISSUE THREAD

**Issue by epicfaace** [actions/setup-java#64]
How does this action determine what version of gradle to use? Is it the latest version? Can we pin the version?

**Comment by joschi** [comment]
@epicfaace Currently, this GitHub action doesn't install Gradle, so it relies on the version installed in the virtual environment, see https://github.com/actions/virtual-environments#available-environments.

As an alternative, you could use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) to specify the version of Gradle to use with your project directly in your repository.

There are also issues/PRs for adding support for installing Gradle/Maven in this GitHub action: #40, #42

**Comment by dmitry-shibanov** [comment]
Closing since answer was provided above.
@joschi Thank you for providing detailed answer.

**Comment by epicfaace** [comment]
Thanks @joschi !
