### ISSUE TITLE
> > > **As a developer** I need to check that metrics collected are correct for content played locally.

### ISSUE THREAD

**Issue by Chuysalgafo** [actions/setup-java#651]
> > > **As a developer** I need to check that metrics collected are correct for content played locally.
> > > 
> > > # Acceptance criteria
> > > 
- [x] > > > - Correct metrics (might be empty) are delivered for a local content.
> > > 
> > > # Tasks
> > > 
> - [x] > - [ ] > - [ ] Add local (small) video to the demo.
> - [x] > - [ ] > - [ ] Check metrics and fix identified issues, if any.
> > 
> > 
> 
> 
> 
> _Publicado originalmente por @Chuysalgafo en https://github.com/SRGSSR/pillarbox-apple/issues/940#issuecomment-2235809313_

_Publicado originalmente por @Chuysalgafo en https://github.com/Chuysalgafo/Identity_Hash/issues/2#issuecomment-2241540282_

**Comment by mahabaleshwars** [comment]
Hello @Chuysalgafo ,

Since this appears to be spam, I am going to close the issue.
