### ISSUE TITLE
> **Description:**

### ISSUE THREAD

**Issue by Chuysalgafo** [actions/setup-java#658]
> **Description:**
> Fix the bug about parsing dragonwell version
> 
> **Related issue:**
> #642 
> 
> **Check list:**
- [x] > - [ ] Mark if documentation changes are required.
- [x] > - [ ] Mark if tests were added or updated to cover the changes.

_Publicado originalmente por @Chuysalgafo en https://github.com/actions/setup-java/pull/643#issuecomment-2235891199_

**Comment by mahabaleshwars** [comment]
Hello @Chuysalgafo ,

Since this appears to be spam, I am going to close the issue.
