### ISSUE TITLE
/usr/bin/tar -xf /home/runner/work/_temp/61d82b15-a59d-4f77-952b-ce66fa49e178/cache.tzst -P -C /home/runner/work/setup-java/setup-java --use-compress-program unzstd

### ISSUE THREAD

**Issue by Chuysalgafo** [actions/setup-java#663]
https://github.com/actions/setup-java/actions/runs/10001779425/job/27646015003

**Comment by mahabaleshwars** [comment]
Hello @Chuysalgafo,
Since this appears to be spam, I am going to close the issue.
