### ISSUE TITLE
Typos on Corretto

### ISSUE THREAD

**Issue by johnshajiang** [actions/setup-java#665]
**Description:**
The codes should use `Corretto` rather than `Coretto`.
For example, `src/distributions/corretto/installer.ts` contains the below line,
```
console.time('Retrieving available versions for Coretto took'); // eslint-disable-line no-console
```
`Coretto` is a typo, and `Corretto` is expected.

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  

**Expected behavior:**
Uses `Corretto` in codes.

**Actual behavior:**
Uses `Coretto` in some codes.

**Comment by gowridurgad** [comment]
Hello @johnshajiang 👋,
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by johnshajiang** [comment]
Thanks for triaging this issue.

I already submitted a PR #666 for it, please take a look at this PR.

**Comment by johnshajiang** [comment]
Thanks for merging the patch from my PR #666.
