### ISSUE TITLE
Support GraalVM 17/21/22

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [actions/setup-java#667]
**Description:**
Support GraalVM 17/21/22

**Justification:**
Building native applications on GitHub pipeline

**Are you willing to submit a PR?**

**Comment by HarithaVattikuti** [comment]
Hello @xuxiaowei-com-cn 
Thank you for creating this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by alazyer** [comment]
also looking forward for this, in order to work with quarkus applications.

**Comment by Marcono1234** [comment]
Not completely sure, but has this been resolved by #501?

Though based on https://github.com/actions/setup-java/pull/501#discussion_r1803652563 I am not sure if those GraalVM versions 17/21/22 will always be available, or if they stop working once that version no longer receives updates under the "GraalVM Free Terms and Conditions (GFTC)".

**Comment by xuxiaowei-com-cn** [comment]
@Marcono1234 Thank you
