### ISSUE TITLE
error message is not optimal on apple silicon with semeru8

### ISSUE THREAD

**Issue by mio-19** [actions/setup-java#673]
**Description:**
```
Run actions/setup-java@v4
  with:
    distribution: semeru
    java-version: 8
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
Installed distributions
  Trying to resolve the latest version from remote
  Error: Unsupported architecture for IBM Semeru: arm64, the following are supported: x64, x86, ppc64le, ppc64, s390x, aarch64
```
**Task version:**
Specify the task version

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by priyagupta108** [comment]
Hello @mio-19 👋,
Thank you for your report. We'll investigate the issue and get back to you.

**Comment by mio-19** [comment]
The error message showed that arm64 is not supported while aarch64 is supported, while in fact only x64 mac is supported

**Comment by mahabaleshwars** [comment]
Hello @mio-19,

We have updated the error message for greater accuracy and fixed a bug related to fetching `aarch64` when `arm64` was requested. Please test your workflow with `actions/setup-java@main`.
Please feel free to reach out to us if you encounter any other issues.
