### ISSUE TITLE
gpg key imported but not trusted

### ISSUE THREAD

**Issue by Jeff-Tian** [actions/setup-java#675]
**Description:**
Set up gpg correctly, but in the `mvn deploy` step failed with message:

```
gpg: no default secret key: No secret key
[GNUPG:] FAILURE sign 17
gpg: signing failed: No secret key
```

**Task version:**
uses: actions/setup-java@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Repro link: https://github.com/Jeff-Tian/keycloak-services-social-weixin/actions/runs/10439001430/job/28907013626

**Expected behavior:**
Deploy success

**Actual behavior:**
Failed.

** Extra Info:**

After many runs with different debugging command, now it seems that the key imported but not trusted.

**Comment by priya-kinthali** [comment]
Hello @Jeff-Tian 👋,
Thank you for reporting this. We will investigate the issue and get back to you as soon as we have updates.

**Comment by mahabaleshwars** [comment]
Hello @Jeff-Tian,

It appears that the issue has been resolved.

The difference between these commands is that ``` gpg --armor export ``` exports a public key in ASCII-armored format, whereas ``` gpg --armor export-secret-keys```  exports a secret/private key in ASCII-armored format.
You will need to provide the secret key and passphrase for GPG to work. 

Please feel free to reach out to us if you encounter any other issues.
