### ISSUE TITLE
Add support for Liberica binaries

### ISSUE THREAD

**Issue by giltene** [actions/setup-java#70]
With work being done towards adding additional binary distributions of OpenJDK as options (likely under the "distro" option, see e.g. https://github.com/actions/setup-java/pull/67), it would be useful to include the Liberica binaries among the distro options

**Comment by tomaszmichalak** [comment]
+1, by default, the Paketo Java buildpack use the Liberica JVM - this buildpack is used by Spring Boot.

**Comment by rafaelargenta-quanto** [comment]
+1, by default, the Paketo Java buildpack use the Liberica JVM - this buildpack is used by Spring Boot.

**Comment by dmitry-shibanov** [comment]
Hello everyone. [Support for Liberica JDK](https://github.com/actions/setup-java/pull/225) was added. I'm going to close the issue.
 - For details see this [Release](https://github.com/actions/setup-java/releases/tag/v2.4.0)
