### ISSUE TITLE
Using custom maven settings.xml to pull the maven dependencies from the remote repository

### ISSUE THREAD

**Issue by loqiu** [actions/setup-java#711]
**Description:**
The settings.xml specified by settings-path will not take effect, the project deployment needs to pull the maven dependencies from the remote repository, but the default settings will blocker all the http requests, and cannot override the mirror.

**Justification:**
```java
      - name: Set up Java version
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
          server-id: nexus-snapshots
          server-username: ${{ secrets.MAVEN_REPO_USERNAME }}
          server-password: ${{ secrets.MAVEN_REPO_PASSWORD }}
          settings-path: ${{ github.workspace }}
      - name: Print workspace path
        run: |
            echo "Workspace Directory: $GITHUB_WORKSPACE"
            ls -la $GITHUB_WORKSPACE
            
      - name: check setting 
        run: cat ${{ github.workspace }}/settings.xml
        
      - name: check mvn setting
        run: mvn help:effective-settings --settings ${{ github.workspace }}/settings.xml
      
      - name: Build with Maven
        run: mvn clean package -s ${{ github.workspace }}/settings.xml -gs /dev/null -X
        
```
![image](https://github.com/user-attachments/assets/e9c567a0-259b-4946-8d50-da9d87c1c82f)
and i put my personal settings.xml in project root directory
i try to overide the settings but it doesn't work, always blocker the request

**Comment by gowridurgad** [comment]
Hello @loqiu,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by loqiu** [comment]
> Hello @loqiu, Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

Thx, i fix with 'overwrite-settings: false' this setting, but although i have overwrite the settings.xml and overwrite the default-http-blocker, i still can't pull the dependency from the remote rep with right username and password, 'i can do it in local'. so the action will block the all http request?
