### ISSUE TITLE
Add support for SapMachine binaries

### ISSUE THREAD

**Issue by giltene** [actions/setup-java#72]
With work being done towards adding additional binary distributions of OpenJDK as options (likely under the "distro" option, see e.g. #67), it would be useful to include the SapMachine binaries among the distro options

**Comment by anilkreddy** [comment]
Is this planned for any upcoming releases to include SapMachine binaries?

**Comment by uluzox** [comment]
I would highly appreciate if Sap Machine JVM would be added to `actions/setup-java`

**Comment by skateball** [comment]
Hi all,
it is merged and [released](https://github.com/actions/setup-java/releases/tag/v4.3.0) some minutes ago.
Have fun
Christian
