### ISSUE TITLE
Why is there no output?

### ISSUE THREAD

**Issue by codecholeric** [actions/setup-java#73]
:warning: Disclaimer: I'm only a beginner with GH actions :wink: 

I'm a little confused, I though according to https://github.com/actions/setup-java/blob/master/action.yml that there would be an output parameter `path` of the action, effectively pointing to the directory of the installed JDK. And in https://github.com/actions/setup-java/blob/master/src/installer.ts I would interprete `core.setOutput('path', toolPath)` to do exactly that :thinking: 

However I've created a little example here: https://github.com/codecholeric/simple-actions/blob/master/.github/workflows/example.yml

And in `Print Output` I don't see any outputs of the step :confused: Am I misunderstanding this?
https://github.com/codecholeric/simple-actions/runs/718201643?check_suite_focus=true

Also, why are there two sorts of naming conventions, the `JAVA_HOME_version.with.dots_x64` and `JAVA_HOME_versionWithoutDots_X64`? The ENV variables with dots somehow cause problems for me, because e.g. Gradle `System.env` seems to just skip those environment variables as having an "illegal" identifier (in Bash I can also not export such a variable?).

**Comment by dmitry-shibanov** [comment]
Hello @codecholeric. If I understood well you want to see result from `core.setOutput` for setup-java step. For this you can use this snippet:
```
    - uses: actions/setup-java@v1
      id: setupJava
      with:
        java-version: 8.x

    - run: echo "${{ toJson(steps.setupJava.outputs) }}"
      shell: bash
```
About the issue with two env variables for `JAVA_HOME` we're planing to remove variant with dots for setup-java@v2: https://github.com/actions/setup-java/blob/61c9e3a719405cb24d9c40bd15467232f9ab55bc/src/installer.ts#L75-L80

**Comment by codecholeric** [comment]
@dmitry-shibanov thanks for the info :smiley: I see that the output path works as expected now! (I don't know why it hasn't when I opened the issue, because I printed steps.setupJava and nothing showed, when I run the same action now, I see

```
steps.setupJava:\ {
  outputs: {
    path: /opt/hostedtoolcache/jdk/9.0.7/x64,
    version: 9.0.7
  },
  outcome: success,
  conclusion: success
}
```

So exactly as I would expect :smile: That means I can probably simplify this beauty here now :joy: https://github.com/TNG/ArchUnit/blob/master/.github/workflows/build.yml#L57

**Comment by codecholeric** [comment]
Gonna close this issue then. I think it's great to drop the env vars with dots :+1:
