### ISSUE TITLE
Improve Maven examples in README

### ISSUE THREAD

**Issue by Marcono1234** [actions/setup-java#75]
Hello,
the Maven examples in the README could probably be improved:
1. Improve command line parameters, see also https://github.com/actions/starter-workflows/pull/538
2. Remove redundant step `name: Build with Maven`, `deploy` already includes `package` so it essentially runs `package` (and all phases before it) twice
Edit: `deploy` would skip compiling (since `package` already did this), but would run tests again.
3. Add `--batch-mode` to `deploy` to prevent output which is intended for interactive console
4. Write out `-s` as `--settings` to make it easier to understand for users who are not familiar with all command line options
5. Change name "Publish to GitHub Packages Apache Maven" to "Publish to GitHub Packages with Maven" to be consistent with other message or drop "with Maven" to be consistent with Gradle step names
6. It might be possible to run `deploy` with `-Dmaven.install.skip=true` to skip installing the package to the local repository since that could cause issues when a cache step is used and a large number of the packages of the project accumulate (only happens if the version of the package changes frequently). Though would be good if someone with more Maven deployment experience could confirm this.

Note that [GitHub Help: Publishing Java packages with Maven](https://help.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-maven) would have to be updated accordingly.

Let me know if you want me to write a pull request.

See also https://github.com/actions/starter-workflows/issues/539

**Comment by dmitry-shibanov** [comment]
Hello @Marcono1234. Thank you for the improvement suggestion. Your proposal looks good. Would you like to submit a pull request ?

**Comment by andrebrait** [comment]
See #129. I would say a shared runner (the most common use-case for most users) should be given more focus on the documentation and eventual tutorials.

**Comment by maxim-lobanov** [comment]
Hello @Marcono1234 , one of your documentation PRs was merged. Do you want to finalize the second one: https://github.com/actions/setup-java/pull/175 ?

**Comment by Marcono1234** [comment]
Hello @maxim-lobanov, sorry for not having responded yet.
I guess the changes would not cause any issues for the Maven GPG Plugin, but I cannot say that for sure. The current commands probably work fine for most cases, so I don't mind that this issue or the pull request is closed now.
Though, if in the future someone wants to pick this work up and continue with it, then I don't mind if they use the changes I proposed.
