### ISSUE TITLE
Log the version of JDK installed

### ISSUE THREAD

**Issue by asarkar** [actions/setup-java#92]
The output from the action doesn't mention the version of JDK installed, which would be very useful to see.

```
Set up JDK
writing /home/runner/.m2/settings.xml
Run actions/setup-java@v1
/bin/tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/temp_540774269 -f /home/runner/work/_temp/a981e5ab-5d0c-4c33-99f2-53d62a23bdf4
creating settings.xml with server-id: github; environment variables: username=$GITHUB_ACTOR, password=$GITHUB_TOKEN, and gpg-passphrase=null
writing /home/runner/.m2/settings.xml
```

**Comment by giltene** [comment]
I too think that reporting (and verifying) the version installed would be generally useful. The simplest way to do this is to execute java -version. One can obviously do that as a step in the job itself, but it would probably be useful (and cheap enough) to do this implicitly in the action as a good logging practice, as the version information is often needs for diagnostic reasons (and the need is usually noticed after the fact, rather than as a planned thing).

**Comment by asarkar** [comment]
Is it possible to implement this seemingly easy ticket instead of waiting for the Big Bang https://github.com/actions/setup-java/issues/98 that could take months or even years?

**Comment by dmitry-shibanov** [comment]
Hello everyone. `Setup-java@v2` was released and it logs version of setup java. Please see migration [guide](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md) from `v1` to `v2`. If you have any concerns feel free to reopen the issue.

**Comment by dmitry-shibanov** [comment]
Hello @asarkar. Thank you for your response and feedback. 
1. We're not planning to make distribution field default one based on [ADR](https://github.com/actions/setup-java/blob/main/docs/adrs/0000-v2-setup-java.md#new-input).
2. Yes, sure. `Setup-java@v2` is more verbose. But I'm not sure, that we should hide this logs. If you have any concerns about it, you can create separate issue to discuss it deeper.

**Comment by asarkar** [comment]
Opened https://github.com/actions/setup-java/issues/157 for verbosity.
