### ISSUE TITLE
Inconsistent compilation

### ISSUE THREAD

**Issue by asarkar** [actions/setup-java#93]
I've [two actions](https://github.com/asarkar/coroutines-test/tree/master/.github/workflows), one for CI, one for publishing, both configured to install JDK 8. On one occasion, compilation passed on the former, but failed on the latter.

**Passed:**
https://github.com/asarkar/coroutines-test/runs/985108815?check_suite_focus=true

**Failed:**
https://github.com/asarkar/coroutines-test/runs/985085884?check_suite_focus=true

**Comment by dmitry-shibanov** [comment]
Hello @asarkar . Does it still reproduce for you?

**Comment by asarkar** [comment]
@dmitry-shibanov Did anything change so as to fix this?

**Comment by dmitry-shibanov** [comment]
Hello @asarkar. Unfortunately I can't see logs because they are expired. I tried to reproduce the issue and step with setup-java task passed without errors. Could you please rerun builds and confirm that everything works as expected ? If it fails, I will be able to check logs for further investigation.

**Comment by asarkar** [comment]
I fixed the problem that wasn’t caught by the compiler, so I can’t reproduce the error without reintroducing the problem. Are the build logs above not helpful? The problem I found is that using the same action, one build fails while the other works.

**Comment by dmitry-shibanov** [comment]
Hello @asarkar . Thank you for response. Unfortunately logs are expired and no longer available. I tried to reproduce the issue and didn't catch the error with setup-java. Could you please provide minimum repro steps to reproduce the issue from our side ?

**Comment by asarkar** [comment]
Closing as not reproducible.
