### ISSUE TITLE
Add support for github pages

### ISSUE THREAD

**Issue by schrepfler** [actions/setup-java#94]
It would be nice to add support for publishing to github pages.
According to this plugin documentation
https://github.github.com/maven-plugins/site-plugin/quickstart.html
It would mean expanding the `settings.xml` template in order to declare github as a server and it's credentials (I haven't seen support for token) and adding instructions on how to add the support in the `pom.xml` file
```
<server>
    <id>github</id>
    <username>YOUR_GITHUB_USERNAME</username>
    <password>YOUR_PASSWORD</password>
</server>
```

**Comment by dmitry-shibanov** [comment]
Hello @schrepfler. I'm going to close the feature request because we're not planing to implement it. The main purpose of the setup-java action is to set up Java and the logic with supporting of GitHub pages looks like of out of scope of the action.
